/**
 * Blog categories and country/region tags are authored in English in Sanity and reused across
 * every locale. This maps the bounded set of values the CMS actually emits onto localized
 * labels; anything unrecognised falls through unchanged so a new tag never renders blank.
 */
import type { Language } from './i18n';

type LocalizedLabel = Record<Exclude<Language, 'en'>, string>;

const CATEGORIES: Record<string, LocalizedLabel> = {
  'Market Access': {
    de: 'Marktzugang',
    fr: 'Accès au marché',
    es: 'Acceso al mercado',
    pt: 'Acesso ao mercado',
    ru: 'Доступ к рынку',
    zh: '市场准入',
    ar: 'الوصول إلى السوق',
  },
  'Regulatory & Policy': {
    de: 'Regulatorik & Politik',
    fr: 'Réglementation et politique',
    es: 'Regulación y políticas',
    pt: 'Regulação e políticas',
    ru: 'Регулирование и политика',
    zh: '监管与政策',
    ar: 'التنظيم والسياسات',
  },
  'Quantitative Research': {
    de: 'Quantitative Forschung',
    fr: 'Recherche quantitative',
    es: 'Investigación cuantitativa',
    pt: 'Pesquisa quantitativa',
    ru: 'Количественные исследования',
    zh: '定量研究',
    ar: 'البحث الكمي',
  },
  'Qualitative Research': {
    de: 'Qualitative Forschung',
    fr: 'Recherche qualitative',
    es: 'Investigación cualitativa',
    pt: 'Pesquisa qualitativa',
    ru: 'Качественные исследования',
    zh: '定性研究',
    ar: 'البحث النوعي',
  },
  'Market Intelligence': {
    de: 'Marktanalyse',
    fr: 'Veille de marché',
    es: 'Inteligencia de mercado',
    pt: 'Inteligência de mercado',
    ru: 'Рыночная аналитика',
    zh: '市场情报',
    ar: 'ذكاء السوق',
  },
  'Digital Health': {
    de: 'Digitale Gesundheit',
    fr: 'Santé numérique',
    es: 'Salud digital',
    pt: 'Saúde digital',
    ru: 'Цифровое здравоохранение',
    zh: '数字健康',
    ar: 'الصحة الرقمية',
  },
  'Clinical Development': {
    de: 'Klinische Entwicklung',
    fr: 'Développement clinique',
    es: 'Desarrollo clínico',
    pt: 'Desenvolvimento clínico',
    ru: 'Клиническая разработка',
    zh: '临床开发',
    ar: 'التطوير السريري',
  },
  'Hospital & Provider': {
    de: 'Kliniken & Leistungserbringer',
    fr: 'Hôpitaux et prestataires',
    es: 'Hospitales y proveedores',
    pt: 'Hospitais e prestadores',
    ru: 'Больницы и поставщики услуг',
    zh: '医院与医疗服务方',
    ar: 'المستشفيات ومقدمو الخدمات',
  },
  'Industry Insights': {
    de: 'Brancheneinblicke',
    fr: 'Analyses sectorielles',
    es: 'Análisis del sector',
    pt: 'Análises do setor',
    ru: 'Отраслевая аналитика',
    zh: '行业洞察',
    ar: 'رؤى القطاع',
  },
  'Commercial Effectiveness': {
    de: 'Kommerzielle Effektivität',
    fr: 'Efficacité commerciale',
    es: 'Eficacia comercial',
    pt: 'Eficácia comercial',
    ru: 'Коммерческая эффективность',
    zh: '商业效能',
    ar: 'الفعالية التجارية',
  },
  'Healthcare Market Research': {
    de: 'Gesundheitsmarktforschung',
    fr: 'Études de marché santé',
    es: 'Investigación de mercado sanitario',
    pt: 'Pesquisa de mercado em saúde',
    ru: 'Исследования рынка здравоохранения',
    zh: '医疗健康市场研究',
    ar: 'أبحاث سوق الرعاية الصحية',
  },
  'Market Research': {
    de: 'Marktforschung',
    fr: 'Études de marché',
    es: 'Investigación de mercado',
    pt: 'Pesquisa de mercado',
    ru: 'Маркетинговые исследования',
    zh: '市场研究',
    ar: 'أبحاث السوق',
  },
  'Medical Devices': {
    de: 'Medizinprodukte',
    fr: 'Dispositifs médicaux',
    es: 'Dispositivos médicos',
    pt: 'Dispositivos médicos',
    ru: 'Медицинские изделия',
    zh: '医疗器械',
    ar: 'الأجهزة الطبية',
  },
  Oncology: {
    de: 'Onkologie',
    fr: 'Oncologie',
    es: 'Oncología',
    pt: 'Oncologia',
    ru: 'Онкология',
    zh: '肿瘤学',
    ar: 'الأورام',
  },
  'Rare Disease': {
    de: 'Seltene Erkrankungen',
    fr: 'Maladies rares',
    es: 'Enfermedades raras',
    pt: 'Doenças raras',
    ru: 'Редкие заболевания',
    zh: '罕见病',
    ar: 'الأمراض النادرة',
  },
};

const REGIONS: Record<string, LocalizedLabel> = {
  China: {
    de: 'China',
    fr: 'Chine',
    es: 'China',
    pt: 'China',
    ru: 'Китай',
    zh: '中国',
    ar: 'الصين',
  },
  Egypt: {
    de: 'Ägypten',
    fr: 'Égypte',
    es: 'Egipto',
    pt: 'Egito',
    ru: 'Египет',
    zh: '埃及',
    ar: 'مصر',
  },
  Europe: {
    de: 'Europa',
    fr: 'Europe',
    es: 'Europa',
    pt: 'Europa',
    ru: 'Европа',
    zh: '欧洲',
    ar: 'أوروبا',
  },
  'Europe and UK': {
    de: 'Europa und UK',
    fr: 'Europe et Royaume-Uni',
    es: 'Europa y Reino Unido',
    pt: 'Europa e Reino Unido',
    ru: 'Европа и Великобритания',
    zh: '欧洲与英国',
    ar: 'أوروبا والمملكة المتحدة',
  },
  GCC: {
    de: 'GCC',
    fr: 'CCG',
    es: 'CCG',
    pt: 'CCG',
    ru: 'ССАГПЗ',
    zh: '海湾合作委员会',
    ar: 'دول مجلس التعاون الخليجي',
  },
  'GCC and MENA': {
    de: 'GCC und MENA',
    fr: 'CCG et MENA',
    es: 'CCG y MENA',
    pt: 'CCG e MENA',
    ru: 'ССАГПЗ и MENA',
    zh: '海湾国家与中东北非',
    ar: 'الخليج والشرق الأوسط وشمال أفريقيا',
  },
  'GCC and global': {
    de: 'GCC und global',
    fr: 'CCG et international',
    es: 'CCG y global',
    pt: 'CCG e global',
    ru: 'ССАГПЗ и весь мир',
    zh: '海湾国家与全球',
    ar: 'الخليج وعالمياً',
  },
  'GCC and multinational': {
    de: 'GCC und multinational',
    fr: 'CCG et multinational',
    es: 'CCG y multinacional',
    pt: 'CCG e multinacional',
    ru: 'ССАГПЗ и международные рынки',
    zh: '海湾国家与跨国市场',
    ar: 'الخليج والأسواق متعددة الجنسيات',
  },
  'GCC oncology': {
    de: 'GCC Onkologie',
    fr: 'Oncologie CCG',
    es: 'Oncología CCG',
    pt: 'Oncologia CCG',
    ru: 'Онкология ССАГПЗ',
    zh: '海湾国家肿瘤领域',
    ar: 'الأورام في الخليج',
  },
  Global: {
    de: 'Global',
    fr: 'International',
    es: 'Global',
    pt: 'Global',
    ru: 'Весь мир',
    zh: '全球',
    ar: 'عالمي',
  },
  'Global / GCC': {
    de: 'Global / GCC',
    fr: 'International / CCG',
    es: 'Global / CCG',
    pt: 'Global / CCG',
    ru: 'Весь мир / ССАГПЗ',
    zh: '全球／海湾国家',
    ar: 'عالمي / الخليج',
  },
  Kuwait: {
    de: 'Kuwait',
    fr: 'Koweït',
    es: 'Kuwait',
    pt: 'Kuwait',
    ru: 'Кувейт',
    zh: '科威特',
    ar: 'الكويت',
  },
  MENA: {
    de: 'MENA',
    fr: 'MENA',
    es: 'MENA',
    pt: 'MENA',
    ru: 'MENA',
    zh: '中东与北非',
    ar: 'الشرق الأوسط وشمال أفريقيا',
  },
  'MENA and Europe': {
    de: 'MENA und Europa',
    fr: 'MENA et Europe',
    es: 'MENA y Europa',
    pt: 'MENA e Europa',
    ru: 'MENA и Европа',
    zh: '中东北非与欧洲',
    ar: 'الشرق الأوسط وشمال أفريقيا وأوروبا',
  },
  'MENA digital health': {
    de: 'MENA Digitale Gesundheit',
    fr: 'Santé numérique MENA',
    es: 'Salud digital MENA',
    pt: 'Saúde digital MENA',
    ru: 'Цифровое здравоохранение MENA',
    zh: '中东北非数字健康',
    ar: 'الصحة الرقمية في الشرق الأوسط وشمال أفريقيا',
  },
  Qatar: {
    de: 'Katar',
    fr: 'Qatar',
    es: 'Catar',
    pt: 'Catar',
    ru: 'Катар',
    zh: '卡塔尔',
    ar: 'قطر',
  },
  'Saudi Arabia': {
    de: 'Saudi-Arabien',
    fr: 'Arabie saoudite',
    es: 'Arabia Saudí',
    pt: 'Arábia Saudita',
    ru: 'Саудовская Аравия',
    zh: '沙特阿拉伯',
    ar: 'المملكة العربية السعودية',
  },
  Singapore: {
    de: 'Singapur',
    fr: 'Singapour',
    es: 'Singapur',
    pt: 'Singapura',
    ru: 'Сингапур',
    zh: '新加坡',
    ar: 'سنغافورة',
  },
  Turkey: {
    de: 'Türkei',
    fr: 'Turquie',
    es: 'Turquía',
    pt: 'Turquia',
    ru: 'Турция',
    zh: '土耳其',
    ar: 'تركيا',
  },
  UAE: {
    de: 'VAE',
    fr: 'EAU',
    es: 'EAU',
    pt: 'EAU',
    ru: 'ОАЭ',
    zh: '阿联酋',
    ar: 'الإمارات',
  },
  'United Arab Emirates': {
    de: 'Vereinigte Arabische Emirate',
    fr: 'Émirats arabes unis',
    es: 'Emiratos Árabes Unidos',
    pt: 'Emirados Árabes Unidos',
    ru: 'Объединённые Арабские Эмираты',
    zh: '阿拉伯联合酋长国',
    ar: 'الإمارات العربية المتحدة',
  },
  'United States': {
    de: 'Vereinigte Staaten',
    fr: 'États-Unis',
    es: 'Estados Unidos',
    pt: 'Estados Unidos',
    ru: 'США',
    zh: '美国',
    ar: 'الولايات المتحدة',
  },
};

const LOOKUP = new Map<string, LocalizedLabel>();
for (const table of [CATEGORIES, REGIONS]) {
  for (const [english, labels] of Object.entries(table)) {
    LOOKUP.set(english.toLowerCase(), labels);
  }
}

/** Localizes a Sanity category or country tag, returning the input when it is not mapped. */
export function localizeBlogTaxonomy(value: string | undefined, language: Language): string {
  if (!value) return '';
  if (language === 'en') return value;
  return LOOKUP.get(value.trim().toLowerCase())?.[language] ?? value;
}
