/**
 * Client-side code-split for remaining marketing / SEO pages (React.lazy).
 * SSR uses lazySeoPages.ssr.ts (eager) via the Vite `ssr-route-split` plugin.
 * Regenerated by scripts/generate-lazy-seo-pages.mjs
 */
import { lazy } from 'react';

export const About = lazy(() => import('@/pages/About'));
export const AccountLevelMarketResearch = lazy(() => import('@/pages/AccountLevelMarketResearch'));
export const ArabicBlogAlsawdyh = lazy(() => import('@/pages/ArabicBlogAlsawdyh'));
export const ArBahthSuqAdwiyahSaudiArabia = lazy(() => import('@/pages/ArBahthSuqAdwiyahSaudiArabia'));
export const ArgentinaPharmaceuticalMarketResearch = lazy(() => import('@/pages/ArgentinaPharmaceuticalMarketResearch'));
export const ArHealthcareMarketResearch = lazy(() => import('@/pages/ArHealthcareMarketResearch'));
export const ArHealthcareMarketResearchSaudiArabia = lazy(() => import('@/pages/ArHealthcareMarketResearchSaudiArabia'));
export const ArPharmaCompaniesDirectoryPage = lazy(() => import('@/pages/templates/ArPharmaCompaniesDirectoryPage'));
export const ArTopHealthcareMarketResearchCompaniesSaudiArabia2026 = lazy(() => import('@/pages/ArTopHealthcareMarketResearchCompaniesSaudiArabia2026'));
export const ArTopMarketResearchCompaniesSaudiArabia2026 = lazy(() => import('@/pages/ArTopMarketResearchCompaniesSaudiArabia2026'));
export const ArTopMarketResearchCompaniesUae2026 = lazy(() => import('@/pages/ArTopMarketResearchCompaniesUae2026'));
export const AustraliaPharmaceuticalMarketResearch = lazy(() => import('@/pages/AustraliaPharmaceuticalMarketResearch'));
export const BahrainPharmaceuticalMarketResearch = lazy(() => import('@/pages/BahrainPharmaceuticalMarketResearch'));
export const BestGlobalMarketResearchCompaniesPharma2026 = lazy(() => import('@/pages/BestGlobalMarketResearchCompaniesPharma2026'));
export const BestObesityWeightManagementMarketResearchFirms2026 = lazy(() => import('@/pages/BestObesityWeightManagementMarketResearchFirms2026'));
export const BestRareDiseaseMarketResearchCompanies2026 = lazy(() => import('@/pages/BestRareDiseaseMarketResearchCompanies2026'));
export const BionixusIndustries = lazy(() => import('@/pages/industries/BionixusIndustries'));
export const BionixusIndustriesInsights = lazy(() => import('@/pages/industries/BionixusIndustriesInsights'));
export const BionixusMiddleEastAfrica = lazy(() => import('@/pages/BionixusMiddleEastAfrica'));
export const BionixusVsIqviaMena = lazy(() => import('@/pages/BionixusVsIqviaMena'));
export const BiosimilarMarketEntrySaudiArabia = lazy(() => import('@/pages/BiosimilarMarketEntrySaudiArabia'));
export const Blog = lazy(() => import('@/pages/Blog'));
export const BrandTrackingPharmaGcc = lazy(() => import('@/pages/BrandTrackingPharmaGcc'));
export const BrazilHealthcareMarketResearch = lazy(() => import('@/pages/BrazilHealthcareMarketResearch'));
export const BrazilPharmaceuticalMarketResearch = lazy(() => import('@/pages/BrazilPharmaceuticalMarketResearch'));
export const BudgetImpactModelSaudiArabia = lazy(() => import('@/pages/BudgetImpactModelSaudiArabia'));
export const CanadaPharmaceuticalMarketResearch = lazy(() => import('@/pages/CanadaPharmaceuticalMarketResearch'));
export const CaseStudies = lazy(() => import('@/pages/CaseStudies'));
export const ChinaPharmaceuticalMarketResearch = lazy(() => import('@/pages/ChinaPharmaceuticalMarketResearch'));
export const ClientReviews = lazy(() => import('@/pages/ClientReviews'));
export const ClinicalDiagnosticsMarketResearch = lazy(() => import('@/pages/ClinicalDiagnosticsMarketResearch'));
export const ClinicalDiagnosticsProposalRequest = lazy(() => import('@/pages/ClinicalDiagnosticsProposalRequest'));
export const CommercialEffectivenessPharmaMiddleEast = lazy(() => import('@/pages/CommercialEffectivenessPharmaMiddleEast'));
export const CompanyDirectoryPage = lazy(() => import('@/pages/templates/CompanyDirectoryPage'));
export const CompetitorAlternativePage = lazy(() => import('@/pages/templates/CompetitorAlternativePage'));
export const ConfPortfolio = lazy(() => import('@/pages/ConfPortfolio'));
export const ConsumerMarketResearchPortal = lazy(() => import('@/pages/ConsumerMarketResearchPortal'));
export const Contact = lazy(() => import('@/pages/Contact'));
export const CostEffectivenessAnalysisGcc = lazy(() => import('@/pages/CostEffectivenessAnalysisGcc'));
export const CostEffectivenessAnalysisSaudiArabia = lazy(() => import('@/pages/CostEffectivenessAnalysisSaudiArabia'));
export const CountryKeywordPage = lazy(() => import('@/pages/templates/CountryKeywordPage'));
export const CountryPage = lazy(() => import('@/pages/healthcare-research/CountryPage'));
export const CountryResearchBriefTemplate = lazy(() => import('@/pages/CountryResearchBriefTemplate'));
export const CrossIndustryMarketResearch = lazy(() => import('@/pages/CrossIndustryMarketResearch'));
export const DeHealthcareMarketResearchGermany = lazy(() => import('@/pages/DeHealthcareMarketResearchGermany'));
export const DenmarkPharmaceuticalMarketResearch = lazy(() => import('@/pages/DenmarkPharmaceuticalMarketResearch'));
export const DesmoidTumorPharmaMarketResearch = lazy(() => import('@/pages/DesmoidTumorPharmaMarketResearch'));
export const DevelopedMarketMedtechListiclePage = lazy(() => import('@/pages/templates/DevelopedMarketMedtechListiclePage'));
export const DevelopedMarketMedtechPage = lazy(() => import('@/pages/templates/DevelopedMarketMedtechPage'));
export const DiabetesMarketResearchUae = lazy(() => import('@/pages/DiabetesMarketResearchUae'));
export const DirectoryHubPage = lazy(() => import('@/pages/templates/DirectoryHubPage'));
export const EgyptPharmaceuticalMarketResearch = lazy(() => import('@/pages/EgyptPharmaceuticalMarketResearch'));
export const EsHealthcareMarketResearchSpain = lazy(() => import('@/pages/EsHealthcareMarketResearchSpain'));
export const EsHubPage = lazy(() => import('@/pages/healthcare-research/EsHubPage'));
export const EsTopHealthcareMarketResearchCompaniesArgentina2026 = lazy(() => import('@/pages/EsTopHealthcareMarketResearchCompaniesArgentina2026'));
export const EsTopMarketResearchCompaniesArgentina2026 = lazy(() => import('@/pages/EsTopMarketResearchCompaniesArgentina2026'));
export const FAQ = lazy(() => import('@/pages/FAQ'));
export const FrancePharmaceuticalMarketResearch = lazy(() => import('@/pages/FrancePharmaceuticalMarketResearch'));
export const FrBionixusMarketResearchMiddleEast = lazy(() => import('@/pages/FrBionixusMarketResearchMiddleEast'));
export const FrFranceCountryPage = lazy(() => import('@/pages/healthcare-research/FrFranceCountryPage'));
export const FrHubPage = lazy(() => import('@/pages/healthcare-research/FrHubPage'));
export const FrQuantitativeHealthcareMarketResearch = lazy(() => import('@/pages/FrQuantitativeHealthcareMarketResearch'));
export const FrStrategicPortfolio = lazy(() => import('@/pages/FrStrategicPortfolio'));
export const GccBiopharmaceuticalsMarket = lazy(() => import('@/pages/market-research-gcc/GccBiopharmaceuticalsMarket'));
export const GccClinicalTrialsMarket = lazy(() => import('@/pages/market-research-gcc/GccClinicalTrialsMarket'));
export const GccGenericInjectablesMarket = lazy(() => import('@/pages/market-research-gcc/GccGenericInjectablesMarket'));
export const GccGenericPharmaceuticalsMarket = lazy(() => import('@/pages/market-research-gcc/GccGenericPharmaceuticalsMarket'));
export const GccHcpRecruitmentMarketResearch = lazy(() => import('@/pages/GccHcpRecruitmentMarketResearch'));
export const GccMarketAccessGuide = lazy(() => import('@/pages/GccMarketAccessGuide'));
export const GccPersonalizedMedicineMarket = lazy(() => import('@/pages/market-research-gcc/GccPersonalizedMedicineMarket'));
export const GccPharmaceuticalMarketResearch = lazy(() => import('@/pages/GccPharmaceuticalMarketResearch'));
export const GccPharmacyMarket = lazy(() => import('@/pages/market-research-gcc/GccPharmacyMarket'));
export const GccPharmaMarketReport2026 = lazy(() => import('@/pages/GccPharmaMarketReport2026'));
export const GermanyPharmaceuticalMarketResearch = lazy(() => import('@/pages/GermanyPharmaceuticalMarketResearch'));
export const GfkAlternativeEgypt = lazy(() => import('@/pages/GfkAlternativeEgypt'));
export const HealthcareFieldworkGcc = lazy(() => import('@/pages/HealthcareFieldworkGcc'));
export const HealthcareFieldworkMiddleEast = lazy(() => import('@/pages/HealthcareFieldworkMiddleEast'));
export const HealthcareMarketResearchAgencyGcc = lazy(() => import('@/pages/HealthcareMarketResearchAgencyGcc'));
export const HealthcareMarketResearchArgentina = lazy(() => import('@/pages/HealthcareMarketResearchArgentina'));
export const HealthcareMarketResearchAustralia = lazy(() => import('@/pages/HealthcareMarketResearchAustralia'));
export const HealthcareMarketResearchCanada = lazy(() => import('@/pages/HealthcareMarketResearchCanada'));
export const HealthcareMarketResearchChina = lazy(() => import('@/pages/HealthcareMarketResearchChina'));
export const HealthcareMarketResearchCompanies2026 = lazy(() => import('@/pages/HealthcareMarketResearchCompanies2026'));
export const HealthcareMarketResearchDenmark = lazy(() => import('@/pages/HealthcareMarketResearchDenmark'));
export const HealthcareMarketResearchFrance = lazy(() => import('@/pages/HealthcareMarketResearchFrance'));
export const HealthcareMarketResearchInBahrain = lazy(() => import('@/pages/HealthcareMarketResearchInBahrain'));
export const HealthcareMarketResearchIndia = lazy(() => import('@/pages/HealthcareMarketResearchIndia'));
export const HealthcareMarketResearchInEgypt = lazy(() => import('@/pages/HealthcareMarketResearchInEgypt'));
export const HealthcareMarketResearchInJordan = lazy(() => import('@/pages/HealthcareMarketResearchInJordan'));
export const HealthcareMarketResearchInKuwait = lazy(() => import('@/pages/HealthcareMarketResearchInKuwait'));
export const HealthcareMarketResearchInOman = lazy(() => import('@/pages/HealthcareMarketResearchInOman'));
export const HealthcareMarketResearchInQatar = lazy(() => import('@/pages/HealthcareMarketResearchInQatar'));
export const HealthcareMarketResearchIreland = lazy(() => import('@/pages/HealthcareMarketResearchIreland'));
export const HealthcareMarketResearchItaly = lazy(() => import('@/pages/HealthcareMarketResearchItaly'));
export const HealthcareMarketResearchJapan = lazy(() => import('@/pages/HealthcareMarketResearchJapan'));
export const HealthcareMarketResearchMalaysia = lazy(() => import('@/pages/HealthcareMarketResearchMalaysia'));
export const HealthcareMarketResearchNetherlands = lazy(() => import('@/pages/HealthcareMarketResearchNetherlands'));
export const HealthcareMarketResearchNewZealand = lazy(() => import('@/pages/HealthcareMarketResearchNewZealand'));
export const HealthcareMarketResearchNorway = lazy(() => import('@/pages/HealthcareMarketResearchNorway'));
export const HealthcareMarketResearchPoland = lazy(() => import('@/pages/HealthcareMarketResearchPoland'));
export const HealthcareMarketResearchSingapore = lazy(() => import('@/pages/HealthcareMarketResearchSingapore'));
export const HealthcareMarketResearchSouthKorea = lazy(() => import('@/pages/HealthcareMarketResearchSouthKorea'));
export const HealthcareMarketResearchSpain = lazy(() => import('@/pages/HealthcareMarketResearchSpain'));
export const HealthcareMarketResearchSweden = lazy(() => import('@/pages/HealthcareMarketResearchSweden'));
export const HealthcareMarketResearchSwitzerland = lazy(() => import('@/pages/HealthcareMarketResearchSwitzerland'));
export const HealthcareMarketResearchTurkey = lazy(() => import('@/pages/HealthcareMarketResearchTurkey'));
export const HealthcareMarketResearchUk = lazy(() => import('@/pages/HealthcareMarketResearchUk'));
export const HealthcareMarketResearchUsa = lazy(() => import('@/pages/HealthcareMarketResearchUsa'));
export const HealthcareMarketStatistics = lazy(() => import('@/pages/HealthcareMarketStatistics'));
export const HealthcareReportsByCountry = lazy(() => import('@/pages/HealthcareReportsByCountry'));
export const HealthcareReportsByTherapy = lazy(() => import('@/pages/HealthcareReportsByTherapy'));
export const HealthcareReportsHub = lazy(() => import('@/pages/HealthcareReportsHub'));
export const HeorConsulting = lazy(() => import('@/pages/HeorConsulting'));
export const HeorConsultingSaudiArabia = lazy(() => import('@/pages/HeorConsultingSaudiArabia'));
export const HtaStudiesSaudiArabia = lazy(() => import('@/pages/HtaStudiesSaudiArabia'));
export const HubPage = lazy(() => import('@/pages/healthcare-research/HubPage'));
export const IndiaPharmaceuticalMarketResearch = lazy(() => import('@/pages/IndiaPharmaceuticalMarketResearch'));
export const IndustryCountryBofuPage = lazy(() => import('@/pages/templates/IndustryCountryBofuPage'));
export const IndustryGlobalHubPage = lazy(() => import('@/pages/IndustryGlobalHubPage'));
export const IndustrySegmentPage = lazy(() => import('@/pages/industries/IndustrySegmentPage'));
export const Insights = lazy(() => import('@/pages/Insights'));
export const IqviaAlternative = lazy(() => import('@/pages/IqviaAlternative'));
export const IrelandPharmaceuticalMarketResearch = lazy(() => import('@/pages/IrelandPharmaceuticalMarketResearch'));
export const ItalyPharmaceuticalMarketResearch = lazy(() => import('@/pages/ItalyPharmaceuticalMarketResearch'));
export const JapanPharmaceuticalMarketResearch = lazy(() => import('@/pages/JapanPharmaceuticalMarketResearch'));
export const JordanPharmaceuticalMarketResearch = lazy(() => import('@/pages/JordanPharmaceuticalMarketResearch'));
export const KantarHealthAlternativeGcc = lazy(() => import('@/pages/KantarHealthAlternativeGcc'));
export const KolMappingSaudiArabiaOncology = lazy(() => import('@/pages/KolMappingSaudiArabiaOncology'));
export const KuwaitMarketAccessResearch = lazy(() => import('@/pages/KuwaitMarketAccessResearch'));
export const KuwaitPharmaceuticalMarketResearch = lazy(() => import('@/pages/KuwaitPharmaceuticalMarketResearch'));
export const LeadingBiologicsBiosimilarsMarketResearchCompanies2026 = lazy(() => import('@/pages/LeadingBiologicsBiosimilarsMarketResearchCompanies2026'));
export const MalaysiaPharmaceuticalMarketResearch = lazy(() => import('@/pages/MalaysiaPharmaceuticalMarketResearch'));
export const MarketAccess = lazy(() => import('@/pages/MarketAccess'));
export const MarketResearch = lazy(() => import('@/pages/MarketResearch'));
export const MarketResearchBahrain = lazy(() => import('@/pages/MarketResearchBahrain'));
export const MarketResearchByIndustry = lazy(() => import('@/pages/MarketResearchByIndustry'));
export const MarketResearchEgypt = lazy(() => import('@/pages/MarketResearchEgypt'));
export const MarketResearchGcc = lazy(() => import('@/pages/MarketResearchGcc'));
export const MarketResearchHealthcare = lazy(() => import('@/pages/MarketResearchHealthcare'));
export const MarketResearchHome = lazy(() => import('@/pages/MarketResearchHome'));
export const MarketResearchInEgypt = lazy(() => import('@/pages/MarketResearchInEgypt'));
export const MarketResearchInSaudiArabia = lazy(() => import('@/pages/MarketResearchInSaudiArabia'));
export const MarketResearchInUae = lazy(() => import('@/pages/MarketResearchInUae'));
export const MarketResearchKsa = lazy(() => import('@/pages/MarketResearchKsa'));
export const MarketResearchKuwait = lazy(() => import('@/pages/MarketResearchKuwait'));
export const MarketResearchOman = lazy(() => import('@/pages/MarketResearchOman'));
export const MarketResearchQatar = lazy(() => import('@/pages/MarketResearchQatar'));
export const MarketResearchSaudi = lazy(() => import('@/pages/MarketResearchSaudi'));
export const MarketResearchSaudiArabiaPharmaceutical = lazy(() => import('@/pages/MarketResearchSaudiArabiaPharmaceutical'));
export const MarketResearchUae = lazy(() => import('@/pages/MarketResearchUae'));
export const Media = lazy(() => import('@/pages/Media'));
export const MedicalAffairsInsightResearchGcc = lazy(() => import('@/pages/MedicalAffairsInsightResearchGcc'));
export const MenaMarketData = lazy(() => import('@/pages/MenaMarketData'));
export const Methodology = lazy(() => import('@/pages/Methodology'));
export const MslInsightResearchMiddleEast = lazy(() => import('@/pages/MslInsightResearchMiddleEast'));
export const MysteryShopRetailBrief = lazy(() => import('@/pages/MysteryShopRetailBrief'));
export const NetherlandsPharmaceuticalMarketResearch = lazy(() => import('@/pages/NetherlandsPharmaceuticalMarketResearch'));
export const NewsHub = lazy(() => import('@/pages/NewsHub'));
export const NewZealandPharmaceuticalMarketResearch = lazy(() => import('@/pages/NewZealandPharmaceuticalMarketResearch'));
export const Nf1PharmaMarketResearch = lazy(() => import('@/pages/Nf1PharmaMarketResearch'));
export const NielsenAlternative = lazy(() => import('@/pages/NielsenAlternative'));
export const NotFound = lazy(() => import('@/pages/NotFound'));
export const OmanPharmaceuticalMarketResearch = lazy(() => import('@/pages/OmanPharmaceuticalMarketResearch'));
export const PatientAdherenceResearchMiddleEast = lazy(() => import('@/pages/PatientAdherenceResearchMiddleEast'));
export const PatientJourneyResearchGcc = lazy(() => import('@/pages/PatientJourneyResearchGcc'));
export const PatientSupportProgramResearchGcc = lazy(() => import('@/pages/PatientSupportProgramResearchGcc'));
export const PharmaceuticalMarketResearchDubai = lazy(() => import('@/pages/PharmaceuticalMarketResearchDubai'));
export const PharmaceuticalMarketResearchProvider = lazy(() => import('@/pages/PharmaceuticalMarketResearchProvider'));
export const PharmaceuticalTherapyAreas = lazy(() => import('@/pages/PharmaceuticalTherapyAreas'));
export const PharmaciesSaudiArabiaMarketing = lazy(() => import('@/pages/PharmaciesSaudiArabiaMarketing'));
export const PharmaFieldworkEgypt = lazy(() => import('@/pages/PharmaFieldworkEgypt'));
export const PharmaFieldworkSaudiArabia = lazy(() => import('@/pages/PharmaFieldworkSaudiArabia'));
export const PharmaFieldworkUae = lazy(() => import('@/pages/PharmaFieldworkUae'));
export const PhysicianSurveySaudiArabia = lazy(() => import('@/pages/PhysicianSurveySaudiArabia'));
export const PolandPharmaceuticalMarketResearch = lazy(() => import('@/pages/PolandPharmaceuticalMarketResearch'));
export const PremiumHomePreview = lazy(() => import('@/pages/PremiumHomePreview'));
export const Pricing = lazy(() => import('@/pages/Pricing'));
export const Privacy = lazy(() => import('@/pages/Privacy'));
export const PtBrazilHealthcareMarketResearch = lazy(() => import('@/pages/PtBrazilHealthcareMarketResearch'));
export const PtBrazilPharmaceuticalMarketResearch = lazy(() => import('@/pages/PtBrazilPharmaceuticalMarketResearch'));
export const PtTopEmpresasPesquisaMercadoBrasil2026 = lazy(() => import('@/pages/PtTopEmpresasPesquisaMercadoBrasil2026'));
export const PtTopHealthcareMarketResearchCompaniesBrazil2026 = lazy(() => import('@/pages/PtTopHealthcareMarketResearchCompaniesBrazil2026'));
export const PtTopMarketResearchCompaniesBrazil2026 = lazy(() => import('@/pages/PtTopMarketResearchCompaniesBrazil2026'));
export const QatarMarketAccessResearch = lazy(() => import('@/pages/QatarMarketAccessResearch'));
export const QatarPharmaceuticalMarketResearch = lazy(() => import('@/pages/QatarPharmaceuticalMarketResearch'));
export const QualitativeMarketResearch = lazy(() => import('@/pages/QualitativeMarketResearch'));
export const QuantitativeHealthcareMarketResearchGuide = lazy(() => import('@/pages/QuantitativeHealthcareMarketResearchGuide'));
export const RealWorldDataHealthcareMiddleEast = lazy(() => import('@/pages/RealWorldDataHealthcareMiddleEast'));
export const RealWorldEvidence = lazy(() => import('@/pages/RealWorldEvidence'));
export const RealWorldEvidenceGcc = lazy(() => import('@/pages/RealWorldEvidenceGcc'));
export const Resources = lazy(() => import('@/pages/Resources'));
export const RespiratoryMarketAccessGcc = lazy(() => import('@/pages/RespiratoryMarketAccessGcc'));
export const SaudiArabiaBiosimilarMarketSizeMethodology2026 = lazy(() => import('@/pages/SaudiArabiaBiosimilarMarketSizeMethodology2026'));
export const SaudiArabiaCancerDiagnosticsMarketSizeMethodology2026 = lazy(() => import('@/pages/SaudiArabiaCancerDiagnosticsMarketSizeMethodology2026'));
export const SaudiArabiaVaccineMarketSizeMethodology2026 = lazy(() => import('@/pages/SaudiArabiaVaccineMarketSizeMethodology2026'));
export const SaudiPayerMarketAccessResearch = lazy(() => import('@/pages/SaudiPayerMarketAccessResearch'));
export const ServiceDetail = lazy(() => import('@/pages/ServiceDetail'));
export const ServicePage = lazy(() => import('@/pages/healthcare-research/ServicePage'));
export const Services = lazy(() => import('@/pages/Services'));
export const SfdaMarketAccessStrategySaudiArabia = lazy(() => import('@/pages/SfdaMarketAccessStrategySaudiArabia'));
export const SingaporePharmaceuticalMarketResearch = lazy(() => import('@/pages/SingaporePharmaceuticalMarketResearch'));
export const SiteMapPage = lazy(() => import('@/pages/SiteMapPage'));
export const SouthKoreaPharmaceuticalMarketResearch = lazy(() => import('@/pages/SouthKoreaPharmaceuticalMarketResearch'));
export const SpainPharmaceuticalMarketResearch = lazy(() => import('@/pages/SpainPharmaceuticalMarketResearch'));
export const SpecialistPhysicianPanelUae = lazy(() => import('@/pages/SpecialistPhysicianPanelUae'));
export const SpecialtyMarketDemandPage = lazy(() => import('@/pages/templates/SpecialtyMarketDemandPage'));
export const SwedenPharmaceuticalMarketResearch = lazy(() => import('@/pages/SwedenPharmaceuticalMarketResearch'));
export const SwitzerlandPharmaceuticalMarketResearch = lazy(() => import('@/pages/SwitzerlandPharmaceuticalMarketResearch'));
export const SyndicatedDataGapTool = lazy(() => import('@/pages/SyndicatedDataGapTool'));
export const Terms = lazy(() => import('@/pages/Terms'));
export const TherapyPage = lazy(() => import('@/pages/healthcare-research/TherapyPage'));
export const TopCompaniesCountryPage = lazy(() => import('@/pages/insights/TopCompaniesCountryPage'));
export const TopConsumerHealthcareMarketResearchFirms2026 = lazy(() => import('@/pages/TopConsumerHealthcareMarketResearchFirms2026'));
export const TopGlobalHealthcareMarketResearchCompanies2026 = lazy(() => import('@/pages/TopGlobalHealthcareMarketResearchCompanies2026'));
export const TopHealthcareMarketResearchCompaniesAbuDhabi2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesAbuDhabi2026'));
export const TopHealthcareMarketResearchCompaniesArgentina2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesArgentina2026'));
export const TopHealthcareMarketResearchCompaniesAustralia2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesAustralia2026'));
export const TopHealthcareMarketResearchCompaniesBrazil2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesBrazil2026'));
export const TopHealthcareMarketResearchCompaniesCanada2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesCanada2026'));
export const TopHealthcareMarketResearchCompaniesChina2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesChina2026'));
export const TopHealthcareMarketResearchCompaniesDenmark2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesDenmark2026'));
export const TopHealthcareMarketResearchCompaniesDubai2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesDubai2026'));
export const TopHealthcareMarketResearchCompaniesEurope2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesEurope2026'));
export const TopHealthcareMarketResearchCompaniesFrance2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesFrance2026'));
export const TopHealthcareMarketResearchCompaniesGermany2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesGermany2026'));
export const TopHealthcareMarketResearchCompaniesIndia2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesIndia2026'));
export const TopHealthcareMarketResearchCompaniesIreland2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesIreland2026'));
export const TopHealthcareMarketResearchCompaniesItaly2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesItaly2026'));
export const TopHealthcareMarketResearchCompaniesJapan2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesJapan2026'));
export const TopHealthcareMarketResearchCompaniesKuwait2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesKuwait2026'));
export const TopHealthcareMarketResearchCompaniesMalaysia2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesMalaysia2026'));
export const TopHealthcareMarketResearchCompaniesMena2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesMena2026'));
export const TopHealthcareMarketResearchCompaniesNetherlands2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesNetherlands2026'));
export const TopHealthcareMarketResearchCompaniesNewZealand2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesNewZealand2026'));
export const TopHealthcareMarketResearchCompaniesNorway2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesNorway2026'));
export const TopHealthcareMarketResearchCompaniesPoland2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesPoland2026'));
export const TopHealthcareMarketResearchCompaniesRiyadh2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesRiyadh2026'));
export const TopHealthcareMarketResearchCompaniesSaudiArabia2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesSaudiArabia2026'));
export const TopHealthcareMarketResearchCompaniesSingapore2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesSingapore2026'));
export const TopHealthcareMarketResearchCompaniesSouthKorea2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesSouthKorea2026'));
export const TopHealthcareMarketResearchCompaniesSpain2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesSpain2026'));
export const TopHealthcareMarketResearchCompaniesSweden2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesSweden2026'));
export const TopHealthcareMarketResearchCompaniesSwitzerland2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesSwitzerland2026'));
export const TopHealthcareMarketResearchCompaniesTurkey2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesTurkey2026'));
export const TopHealthcareMarketResearchCompaniesUae2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesUae2026'));
export const TopHealthcareMarketResearchCompaniesUk2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesUk2026'));
export const TopHealthcareMarketResearchCompaniesUsa2026 = lazy(() => import('@/pages/TopHealthcareMarketResearchCompaniesUsa2026'));
export const TopHematologyMarketResearchCompanies2026 = lazy(() => import('@/pages/TopHematologyMarketResearchCompanies2026'));
export const TopIndustryMarketResearchListicle = lazy(() => import('@/pages/templates/TopIndustryMarketResearchListicle'));
export const TopMarketResearchCompaniesAbuDhabi2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesAbuDhabi2026'));
export const TopMarketResearchCompaniesArgentina2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesArgentina2026'));
export const TopMarketResearchCompaniesAustralia2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesAustralia2026'));
export const TopMarketResearchCompaniesBrazil2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesBrazil2026'));
export const TopMarketResearchCompaniesCanada2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesCanada2026'));
export const TopMarketResearchCompaniesChina2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesChina2026'));
export const TopMarketResearchCompaniesDenmark2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesDenmark2026'));
export const TopMarketResearchCompaniesDubai2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesDubai2026'));
export const TopMarketResearchCompaniesEgypt2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesEgypt2026'));
export const TopMarketResearchCompaniesFrance2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesFrance2026'));
export const TopMarketResearchCompaniesGcc2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesGcc2026'));
export const TopMarketResearchCompaniesGermany2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesGermany2026'));
export const TopMarketResearchCompaniesIndia2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesIndia2026'));
export const TopMarketResearchCompaniesIreland2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesIreland2026'));
export const TopMarketResearchCompaniesItaly2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesItaly2026'));
export const TopMarketResearchCompaniesJapan2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesJapan2026'));
export const TopMarketResearchCompaniesMalaysia2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesMalaysia2026'));
export const TopMarketResearchCompaniesNetherlands2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesNetherlands2026'));
export const TopMarketResearchCompaniesNewZealand2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesNewZealand2026'));
export const TopMarketResearchCompaniesPoland2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesPoland2026'));
export const TopMarketResearchCompaniesRiyadh2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesRiyadh2026'));
export const TopMarketResearchCompaniesSaudiArabia2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesSaudiArabia2026'));
export const TopMarketResearchCompaniesSingapore2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesSingapore2026'));
export const TopMarketResearchCompaniesSouthKorea2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesSouthKorea2026'));
export const TopMarketResearchCompaniesSpain2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesSpain2026'));
export const TopMarketResearchCompaniesSweden2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesSweden2026'));
export const TopMarketResearchCompaniesSwitzerland2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesSwitzerland2026'));
export const TopMarketResearchCompaniesTurkey2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesTurkey2026'));
export const TopMarketResearchCompaniesUae2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesUae2026'));
export const TopMarketResearchCompaniesUk2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesUk2026'));
export const TopMarketResearchCompaniesUsa2026 = lazy(() => import('@/pages/TopMarketResearchCompaniesUsa2026'));
export const TopOncologyMarketResearchCompanies2026 = lazy(() => import('@/pages/TopOncologyMarketResearchCompanies2026'));
export const TopPharmaceuticalAnalyticsCompaniesWorldwide2026 = lazy(() => import('@/pages/TopPharmaceuticalAnalyticsCompaniesWorldwide2026'));
export const TopPharmaMarketResearchCompaniesMiddleEast2026 = lazy(() => import('@/pages/TopPharmaMarketResearchCompaniesMiddleEast2026'));
export const TurkeyPharmaceuticalMarketResearch = lazy(() => import('@/pages/TurkeyPharmaceuticalMarketResearch'));
export const UaeMarketAccessResearch = lazy(() => import('@/pages/UaeMarketAccessResearch'));
export const UaePharmaceuticalMarketResearch = lazy(() => import('@/pages/UaePharmaceuticalMarketResearch'));
export const UaePricingReimbursementStrategy = lazy(() => import('@/pages/UaePricingReimbursementStrategy'));
export const UkPharmaceuticalMarketResearch = lazy(() => import('@/pages/UkPharmaceuticalMarketResearch'));
export const UsaPharmaceuticalMarketResearch = lazy(() => import('@/pages/UsaPharmaceuticalMarketResearch'));
export const VerifyEmail = lazy(() => import('@/pages/VerifyEmail'));
export const VideosIndex = lazy(() => import('@/pages/VideosIndex'));
export const WhatIsMarketStudy = lazy(() => import('@/pages/WhatIsMarketStudy'));
export const ZhBionixusMarketResearchMiddleEast = lazy(() => import('@/pages/ZhBionixusMarketResearchMiddleEast'));
export const ZhStrategicPortfolio = lazy(() => import('@/pages/ZhStrategicPortfolio'));
export const ZhTopMarketResearchCompaniesEgypt2026 = lazy(() => import('@/pages/ZhTopMarketResearchCompaniesEgypt2026'));
export const TopConsumerInsightsCompaniesKsa2026 = lazy(
  () => import('@/pages/TopConsumerInsightsCompaniesKsa2026'),
);
export const TopConsumerInsightsCompaniesSaudiArabiaRedirect = lazy(() =>
  import('@/pages/TopConsumerInsightsCompaniesKsa2026').then((m) => ({ default: m.TopConsumerInsightsCompaniesSaudiArabiaRedirect })),
);

const seoPageLoaders: Record<string, () => Promise<unknown>> = {
  "About": () => import('@/pages/About'),
  "AccountLevelMarketResearch": () => import('@/pages/AccountLevelMarketResearch'),
  "ArabicBlogAlsawdyh": () => import('@/pages/ArabicBlogAlsawdyh'),
  "ArBahthSuqAdwiyahSaudiArabia": () => import('@/pages/ArBahthSuqAdwiyahSaudiArabia'),
  "ArgentinaPharmaceuticalMarketResearch": () => import('@/pages/ArgentinaPharmaceuticalMarketResearch'),
  "ArHealthcareMarketResearch": () => import('@/pages/ArHealthcareMarketResearch'),
  "ArHealthcareMarketResearchSaudiArabia": () => import('@/pages/ArHealthcareMarketResearchSaudiArabia'),
  "ArPharmaCompaniesDirectoryPage": () => import('@/pages/templates/ArPharmaCompaniesDirectoryPage'),
  "ArTopHealthcareMarketResearchCompaniesSaudiArabia2026": () => import('@/pages/ArTopHealthcareMarketResearchCompaniesSaudiArabia2026'),
  "ArTopMarketResearchCompaniesSaudiArabia2026": () => import('@/pages/ArTopMarketResearchCompaniesSaudiArabia2026'),
  "ArTopMarketResearchCompaniesUae2026": () => import('@/pages/ArTopMarketResearchCompaniesUae2026'),
  "AustraliaPharmaceuticalMarketResearch": () => import('@/pages/AustraliaPharmaceuticalMarketResearch'),
  "BahrainPharmaceuticalMarketResearch": () => import('@/pages/BahrainPharmaceuticalMarketResearch'),
  "BestGlobalMarketResearchCompaniesPharma2026": () => import('@/pages/BestGlobalMarketResearchCompaniesPharma2026'),
  "BestObesityWeightManagementMarketResearchFirms2026": () => import('@/pages/BestObesityWeightManagementMarketResearchFirms2026'),
  "BestRareDiseaseMarketResearchCompanies2026": () => import('@/pages/BestRareDiseaseMarketResearchCompanies2026'),
  "BionixusIndustries": () => import('@/pages/industries/BionixusIndustries'),
  "BionixusIndustriesInsights": () => import('@/pages/industries/BionixusIndustriesInsights'),
  "BionixusMiddleEastAfrica": () => import('@/pages/BionixusMiddleEastAfrica'),
  "BionixusVsIqviaMena": () => import('@/pages/BionixusVsIqviaMena'),
  "BiosimilarMarketEntrySaudiArabia": () => import('@/pages/BiosimilarMarketEntrySaudiArabia'),
  "Blog": () => import('@/pages/Blog'),
  "BrandTrackingPharmaGcc": () => import('@/pages/BrandTrackingPharmaGcc'),
  "BrazilHealthcareMarketResearch": () => import('@/pages/BrazilHealthcareMarketResearch'),
  "BrazilPharmaceuticalMarketResearch": () => import('@/pages/BrazilPharmaceuticalMarketResearch'),
  "BudgetImpactModelSaudiArabia": () => import('@/pages/BudgetImpactModelSaudiArabia'),
  "CanadaPharmaceuticalMarketResearch": () => import('@/pages/CanadaPharmaceuticalMarketResearch'),
  "CaseStudies": () => import('@/pages/CaseStudies'),
  "ChinaPharmaceuticalMarketResearch": () => import('@/pages/ChinaPharmaceuticalMarketResearch'),
  "ClientReviews": () => import('@/pages/ClientReviews'),
  "ClinicalDiagnosticsMarketResearch": () => import('@/pages/ClinicalDiagnosticsMarketResearch'),
  "ClinicalDiagnosticsProposalRequest": () => import('@/pages/ClinicalDiagnosticsProposalRequest'),
  "CommercialEffectivenessPharmaMiddleEast": () => import('@/pages/CommercialEffectivenessPharmaMiddleEast'),
  "CompanyDirectoryPage": () => import('@/pages/templates/CompanyDirectoryPage'),
  "CompetitorAlternativePage": () => import('@/pages/templates/CompetitorAlternativePage'),
  "ConfPortfolio": () => import('@/pages/ConfPortfolio'),
  "ConsumerMarketResearchPortal": () => import('@/pages/ConsumerMarketResearchPortal'),
  "Contact": () => import('@/pages/Contact'),
  "CostEffectivenessAnalysisGcc": () => import('@/pages/CostEffectivenessAnalysisGcc'),
  "CostEffectivenessAnalysisSaudiArabia": () => import('@/pages/CostEffectivenessAnalysisSaudiArabia'),
  "CountryKeywordPage": () => import('@/pages/templates/CountryKeywordPage'),
  "CountryPage": () => import('@/pages/healthcare-research/CountryPage'),
  "CountryResearchBriefTemplate": () => import('@/pages/CountryResearchBriefTemplate'),
  "CrossIndustryMarketResearch": () => import('@/pages/CrossIndustryMarketResearch'),
  "DeHealthcareMarketResearchGermany": () => import('@/pages/DeHealthcareMarketResearchGermany'),
  "DenmarkPharmaceuticalMarketResearch": () => import('@/pages/DenmarkPharmaceuticalMarketResearch'),
  "DesmoidTumorPharmaMarketResearch": () => import('@/pages/DesmoidTumorPharmaMarketResearch'),
  "DevelopedMarketMedtechListiclePage": () => import('@/pages/templates/DevelopedMarketMedtechListiclePage'),
  "DevelopedMarketMedtechPage": () => import('@/pages/templates/DevelopedMarketMedtechPage'),
  "DiabetesMarketResearchUae": () => import('@/pages/DiabetesMarketResearchUae'),
  "DirectoryHubPage": () => import('@/pages/templates/DirectoryHubPage'),
  "EgyptPharmaceuticalMarketResearch": () => import('@/pages/EgyptPharmaceuticalMarketResearch'),
  "EsHealthcareMarketResearchSpain": () => import('@/pages/EsHealthcareMarketResearchSpain'),
  "EsHubPage": () => import('@/pages/healthcare-research/EsHubPage'),
  "EsTopHealthcareMarketResearchCompaniesArgentina2026": () => import('@/pages/EsTopHealthcareMarketResearchCompaniesArgentina2026'),
  "EsTopMarketResearchCompaniesArgentina2026": () => import('@/pages/EsTopMarketResearchCompaniesArgentina2026'),
  "FAQ": () => import('@/pages/FAQ'),
  "FrancePharmaceuticalMarketResearch": () => import('@/pages/FrancePharmaceuticalMarketResearch'),
  "FrBionixusMarketResearchMiddleEast": () => import('@/pages/FrBionixusMarketResearchMiddleEast'),
  "FrFranceCountryPage": () => import('@/pages/healthcare-research/FrFranceCountryPage'),
  "FrHubPage": () => import('@/pages/healthcare-research/FrHubPage'),
  "FrQuantitativeHealthcareMarketResearch": () => import('@/pages/FrQuantitativeHealthcareMarketResearch'),
  "FrStrategicPortfolio": () => import('@/pages/FrStrategicPortfolio'),
  "GccBiopharmaceuticalsMarket": () => import('@/pages/market-research-gcc/GccBiopharmaceuticalsMarket'),
  "GccClinicalTrialsMarket": () => import('@/pages/market-research-gcc/GccClinicalTrialsMarket'),
  "GccGenericInjectablesMarket": () => import('@/pages/market-research-gcc/GccGenericInjectablesMarket'),
  "GccGenericPharmaceuticalsMarket": () => import('@/pages/market-research-gcc/GccGenericPharmaceuticalsMarket'),
  "GccHcpRecruitmentMarketResearch": () => import('@/pages/GccHcpRecruitmentMarketResearch'),
  "GccMarketAccessGuide": () => import('@/pages/GccMarketAccessGuide'),
  "GccPersonalizedMedicineMarket": () => import('@/pages/market-research-gcc/GccPersonalizedMedicineMarket'),
  "GccPharmaceuticalMarketResearch": () => import('@/pages/GccPharmaceuticalMarketResearch'),
  "GccPharmacyMarket": () => import('@/pages/market-research-gcc/GccPharmacyMarket'),
  "GccPharmaMarketReport2026": () => import('@/pages/GccPharmaMarketReport2026'),
  "GermanyPharmaceuticalMarketResearch": () => import('@/pages/GermanyPharmaceuticalMarketResearch'),
  "GfkAlternativeEgypt": () => import('@/pages/GfkAlternativeEgypt'),
  "HealthcareFieldworkGcc": () => import('@/pages/HealthcareFieldworkGcc'),
  "HealthcareFieldworkMiddleEast": () => import('@/pages/HealthcareFieldworkMiddleEast'),
  "HealthcareMarketResearchAgencyGcc": () => import('@/pages/HealthcareMarketResearchAgencyGcc'),
  "HealthcareMarketResearchArgentina": () => import('@/pages/HealthcareMarketResearchArgentina'),
  "HealthcareMarketResearchAustralia": () => import('@/pages/HealthcareMarketResearchAustralia'),
  "HealthcareMarketResearchCanada": () => import('@/pages/HealthcareMarketResearchCanada'),
  "HealthcareMarketResearchChina": () => import('@/pages/HealthcareMarketResearchChina'),
  "HealthcareMarketResearchCompanies2026": () => import('@/pages/HealthcareMarketResearchCompanies2026'),
  "HealthcareMarketResearchDenmark": () => import('@/pages/HealthcareMarketResearchDenmark'),
  "HealthcareMarketResearchFrance": () => import('@/pages/HealthcareMarketResearchFrance'),
  "HealthcareMarketResearchInBahrain": () => import('@/pages/HealthcareMarketResearchInBahrain'),
  "HealthcareMarketResearchIndia": () => import('@/pages/HealthcareMarketResearchIndia'),
  "HealthcareMarketResearchInEgypt": () => import('@/pages/HealthcareMarketResearchInEgypt'),
  "HealthcareMarketResearchInJordan": () => import('@/pages/HealthcareMarketResearchInJordan'),
  "HealthcareMarketResearchInKuwait": () => import('@/pages/HealthcareMarketResearchInKuwait'),
  "HealthcareMarketResearchInOman": () => import('@/pages/HealthcareMarketResearchInOman'),
  "HealthcareMarketResearchInQatar": () => import('@/pages/HealthcareMarketResearchInQatar'),
  "HealthcareMarketResearchIreland": () => import('@/pages/HealthcareMarketResearchIreland'),
  "HealthcareMarketResearchItaly": () => import('@/pages/HealthcareMarketResearchItaly'),
  "HealthcareMarketResearchJapan": () => import('@/pages/HealthcareMarketResearchJapan'),
  "HealthcareMarketResearchMalaysia": () => import('@/pages/HealthcareMarketResearchMalaysia'),
  "HealthcareMarketResearchNetherlands": () => import('@/pages/HealthcareMarketResearchNetherlands'),
  "HealthcareMarketResearchNewZealand": () => import('@/pages/HealthcareMarketResearchNewZealand'),
  "HealthcareMarketResearchNorway": () => import('@/pages/HealthcareMarketResearchNorway'),
  "HealthcareMarketResearchPoland": () => import('@/pages/HealthcareMarketResearchPoland'),
  "HealthcareMarketResearchSingapore": () => import('@/pages/HealthcareMarketResearchSingapore'),
  "HealthcareMarketResearchSouthKorea": () => import('@/pages/HealthcareMarketResearchSouthKorea'),
  "HealthcareMarketResearchSpain": () => import('@/pages/HealthcareMarketResearchSpain'),
  "HealthcareMarketResearchSweden": () => import('@/pages/HealthcareMarketResearchSweden'),
  "HealthcareMarketResearchSwitzerland": () => import('@/pages/HealthcareMarketResearchSwitzerland'),
  "HealthcareMarketResearchTurkey": () => import('@/pages/HealthcareMarketResearchTurkey'),
  "HealthcareMarketResearchUk": () => import('@/pages/HealthcareMarketResearchUk'),
  "HealthcareMarketResearchUsa": () => import('@/pages/HealthcareMarketResearchUsa'),
  "HealthcareMarketStatistics": () => import('@/pages/HealthcareMarketStatistics'),
  "HealthcareReportsByCountry": () => import('@/pages/HealthcareReportsByCountry'),
  "HealthcareReportsByTherapy": () => import('@/pages/HealthcareReportsByTherapy'),
  "HealthcareReportsHub": () => import('@/pages/HealthcareReportsHub'),
  "HeorConsulting": () => import('@/pages/HeorConsulting'),
  "HeorConsultingSaudiArabia": () => import('@/pages/HeorConsultingSaudiArabia'),
  "HtaStudiesSaudiArabia": () => import('@/pages/HtaStudiesSaudiArabia'),
  "HubPage": () => import('@/pages/healthcare-research/HubPage'),
  "IndiaPharmaceuticalMarketResearch": () => import('@/pages/IndiaPharmaceuticalMarketResearch'),
  "IndustryCountryBofuPage": () => import('@/pages/templates/IndustryCountryBofuPage'),
  "IndustryGlobalHubPage": () => import('@/pages/IndustryGlobalHubPage'),
  "IndustrySegmentPage": () => import('@/pages/industries/IndustrySegmentPage'),
  "Insights": () => import('@/pages/Insights'),
  "IqviaAlternative": () => import('@/pages/IqviaAlternative'),
  "IrelandPharmaceuticalMarketResearch": () => import('@/pages/IrelandPharmaceuticalMarketResearch'),
  "ItalyPharmaceuticalMarketResearch": () => import('@/pages/ItalyPharmaceuticalMarketResearch'),
  "JapanPharmaceuticalMarketResearch": () => import('@/pages/JapanPharmaceuticalMarketResearch'),
  "JordanPharmaceuticalMarketResearch": () => import('@/pages/JordanPharmaceuticalMarketResearch'),
  "KantarHealthAlternativeGcc": () => import('@/pages/KantarHealthAlternativeGcc'),
  "KolMappingSaudiArabiaOncology": () => import('@/pages/KolMappingSaudiArabiaOncology'),
  "KuwaitMarketAccessResearch": () => import('@/pages/KuwaitMarketAccessResearch'),
  "KuwaitPharmaceuticalMarketResearch": () => import('@/pages/KuwaitPharmaceuticalMarketResearch'),
  "LeadingBiologicsBiosimilarsMarketResearchCompanies2026": () => import('@/pages/LeadingBiologicsBiosimilarsMarketResearchCompanies2026'),
  "MalaysiaPharmaceuticalMarketResearch": () => import('@/pages/MalaysiaPharmaceuticalMarketResearch'),
  "MarketAccess": () => import('@/pages/MarketAccess'),
  "MarketResearch": () => import('@/pages/MarketResearch'),
  "MarketResearchBahrain": () => import('@/pages/MarketResearchBahrain'),
  "MarketResearchByIndustry": () => import('@/pages/MarketResearchByIndustry'),
  "MarketResearchEgypt": () => import('@/pages/MarketResearchEgypt'),
  "MarketResearchGcc": () => import('@/pages/MarketResearchGcc'),
  "MarketResearchHealthcare": () => import('@/pages/MarketResearchHealthcare'),
  "MarketResearchHome": () => import('@/pages/MarketResearchHome'),
  "MarketResearchInEgypt": () => import('@/pages/MarketResearchInEgypt'),
  "MarketResearchInSaudiArabia": () => import('@/pages/MarketResearchInSaudiArabia'),
  "MarketResearchInUae": () => import('@/pages/MarketResearchInUae'),
  "MarketResearchKsa": () => import('@/pages/MarketResearchKsa'),
  "MarketResearchKuwait": () => import('@/pages/MarketResearchKuwait'),
  "MarketResearchOman": () => import('@/pages/MarketResearchOman'),
  "MarketResearchQatar": () => import('@/pages/MarketResearchQatar'),
  "MarketResearchSaudi": () => import('@/pages/MarketResearchSaudi'),
  "MarketResearchSaudiArabiaPharmaceutical": () => import('@/pages/MarketResearchSaudiArabiaPharmaceutical'),
  "MarketResearchUae": () => import('@/pages/MarketResearchUae'),
  "Media": () => import('@/pages/Media'),
  "MedicalAffairsInsightResearchGcc": () => import('@/pages/MedicalAffairsInsightResearchGcc'),
  "MenaMarketData": () => import('@/pages/MenaMarketData'),
  "Methodology": () => import('@/pages/Methodology'),
  "MslInsightResearchMiddleEast": () => import('@/pages/MslInsightResearchMiddleEast'),
  "MysteryShopRetailBrief": () => import('@/pages/MysteryShopRetailBrief'),
  "NetherlandsPharmaceuticalMarketResearch": () => import('@/pages/NetherlandsPharmaceuticalMarketResearch'),
  "NewsHub": () => import('@/pages/NewsHub'),
  "NewZealandPharmaceuticalMarketResearch": () => import('@/pages/NewZealandPharmaceuticalMarketResearch'),
  "Nf1PharmaMarketResearch": () => import('@/pages/Nf1PharmaMarketResearch'),
  "NielsenAlternative": () => import('@/pages/NielsenAlternative'),
  "NotFound": () => import('@/pages/NotFound'),
  "OmanPharmaceuticalMarketResearch": () => import('@/pages/OmanPharmaceuticalMarketResearch'),
  "PatientAdherenceResearchMiddleEast": () => import('@/pages/PatientAdherenceResearchMiddleEast'),
  "PatientJourneyResearchGcc": () => import('@/pages/PatientJourneyResearchGcc'),
  "PatientSupportProgramResearchGcc": () => import('@/pages/PatientSupportProgramResearchGcc'),
  "PharmaceuticalMarketResearchDubai": () => import('@/pages/PharmaceuticalMarketResearchDubai'),
  "PharmaceuticalMarketResearchProvider": () => import('@/pages/PharmaceuticalMarketResearchProvider'),
  "PharmaceuticalTherapyAreas": () => import('@/pages/PharmaceuticalTherapyAreas'),
  "PharmaciesSaudiArabiaMarketing": () => import('@/pages/PharmaciesSaudiArabiaMarketing'),
  "PharmaFieldworkEgypt": () => import('@/pages/PharmaFieldworkEgypt'),
  "PharmaFieldworkSaudiArabia": () => import('@/pages/PharmaFieldworkSaudiArabia'),
  "PharmaFieldworkUae": () => import('@/pages/PharmaFieldworkUae'),
  "PhysicianSurveySaudiArabia": () => import('@/pages/PhysicianSurveySaudiArabia'),
  "PolandPharmaceuticalMarketResearch": () => import('@/pages/PolandPharmaceuticalMarketResearch'),
  "PremiumHomePreview": () => import('@/pages/PremiumHomePreview'),
  "Pricing": () => import('@/pages/Pricing'),
  "Privacy": () => import('@/pages/Privacy'),
  "PtBrazilHealthcareMarketResearch": () => import('@/pages/PtBrazilHealthcareMarketResearch'),
  "PtBrazilPharmaceuticalMarketResearch": () => import('@/pages/PtBrazilPharmaceuticalMarketResearch'),
  "PtTopEmpresasPesquisaMercadoBrasil2026": () => import('@/pages/PtTopEmpresasPesquisaMercadoBrasil2026'),
  "PtTopHealthcareMarketResearchCompaniesBrazil2026": () => import('@/pages/PtTopHealthcareMarketResearchCompaniesBrazil2026'),
  "PtTopMarketResearchCompaniesBrazil2026": () => import('@/pages/PtTopMarketResearchCompaniesBrazil2026'),
  "QatarMarketAccessResearch": () => import('@/pages/QatarMarketAccessResearch'),
  "QatarPharmaceuticalMarketResearch": () => import('@/pages/QatarPharmaceuticalMarketResearch'),
  "QualitativeMarketResearch": () => import('@/pages/QualitativeMarketResearch'),
  "QuantitativeHealthcareMarketResearchGuide": () => import('@/pages/QuantitativeHealthcareMarketResearchGuide'),
  "RealWorldDataHealthcareMiddleEast": () => import('@/pages/RealWorldDataHealthcareMiddleEast'),
  "RealWorldEvidence": () => import('@/pages/RealWorldEvidence'),
  "RealWorldEvidenceGcc": () => import('@/pages/RealWorldEvidenceGcc'),
  "Resources": () => import('@/pages/Resources'),
  "RespiratoryMarketAccessGcc": () => import('@/pages/RespiratoryMarketAccessGcc'),
  "SaudiArabiaBiosimilarMarketSizeMethodology2026": () => import('@/pages/SaudiArabiaBiosimilarMarketSizeMethodology2026'),
  "SaudiArabiaCancerDiagnosticsMarketSizeMethodology2026": () => import('@/pages/SaudiArabiaCancerDiagnosticsMarketSizeMethodology2026'),
  "SaudiArabiaVaccineMarketSizeMethodology2026": () => import('@/pages/SaudiArabiaVaccineMarketSizeMethodology2026'),
  "SaudiPayerMarketAccessResearch": () => import('@/pages/SaudiPayerMarketAccessResearch'),
  "ServiceDetail": () => import('@/pages/ServiceDetail'),
  "ServicePage": () => import('@/pages/healthcare-research/ServicePage'),
  "Services": () => import('@/pages/Services'),
  "SfdaMarketAccessStrategySaudiArabia": () => import('@/pages/SfdaMarketAccessStrategySaudiArabia'),
  "SingaporePharmaceuticalMarketResearch": () => import('@/pages/SingaporePharmaceuticalMarketResearch'),
  "SiteMapPage": () => import('@/pages/SiteMapPage'),
  "SouthKoreaPharmaceuticalMarketResearch": () => import('@/pages/SouthKoreaPharmaceuticalMarketResearch'),
  "SpainPharmaceuticalMarketResearch": () => import('@/pages/SpainPharmaceuticalMarketResearch'),
  "SpecialistPhysicianPanelUae": () => import('@/pages/SpecialistPhysicianPanelUae'),
  "SpecialtyMarketDemandPage": () => import('@/pages/templates/SpecialtyMarketDemandPage'),
  "SwedenPharmaceuticalMarketResearch": () => import('@/pages/SwedenPharmaceuticalMarketResearch'),
  "SwitzerlandPharmaceuticalMarketResearch": () => import('@/pages/SwitzerlandPharmaceuticalMarketResearch'),
  "SyndicatedDataGapTool": () => import('@/pages/SyndicatedDataGapTool'),
  "Terms": () => import('@/pages/Terms'),
  "TherapyPage": () => import('@/pages/healthcare-research/TherapyPage'),
  "TopCompaniesCountryPage": () => import('@/pages/insights/TopCompaniesCountryPage'),
  "TopConsumerHealthcareMarketResearchFirms2026": () => import('@/pages/TopConsumerHealthcareMarketResearchFirms2026'),
  "TopGlobalHealthcareMarketResearchCompanies2026": () => import('@/pages/TopGlobalHealthcareMarketResearchCompanies2026'),
  "TopHealthcareMarketResearchCompaniesAbuDhabi2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesAbuDhabi2026'),
  "TopHealthcareMarketResearchCompaniesArgentina2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesArgentina2026'),
  "TopHealthcareMarketResearchCompaniesAustralia2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesAustralia2026'),
  "TopHealthcareMarketResearchCompaniesBrazil2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesBrazil2026'),
  "TopHealthcareMarketResearchCompaniesCanada2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesCanada2026'),
  "TopHealthcareMarketResearchCompaniesChina2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesChina2026'),
  "TopHealthcareMarketResearchCompaniesDenmark2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesDenmark2026'),
  "TopHealthcareMarketResearchCompaniesDubai2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesDubai2026'),
  "TopHealthcareMarketResearchCompaniesEurope2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesEurope2026'),
  "TopHealthcareMarketResearchCompaniesFrance2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesFrance2026'),
  "TopHealthcareMarketResearchCompaniesGermany2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesGermany2026'),
  "TopHealthcareMarketResearchCompaniesIndia2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesIndia2026'),
  "TopHealthcareMarketResearchCompaniesIreland2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesIreland2026'),
  "TopHealthcareMarketResearchCompaniesItaly2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesItaly2026'),
  "TopHealthcareMarketResearchCompaniesJapan2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesJapan2026'),
  "TopHealthcareMarketResearchCompaniesKuwait2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesKuwait2026'),
  "TopHealthcareMarketResearchCompaniesMalaysia2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesMalaysia2026'),
  "TopHealthcareMarketResearchCompaniesMena2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesMena2026'),
  "TopHealthcareMarketResearchCompaniesNetherlands2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesNetherlands2026'),
  "TopHealthcareMarketResearchCompaniesNewZealand2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesNewZealand2026'),
  "TopHealthcareMarketResearchCompaniesNorway2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesNorway2026'),
  "TopHealthcareMarketResearchCompaniesPoland2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesPoland2026'),
  "TopHealthcareMarketResearchCompaniesRiyadh2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesRiyadh2026'),
  "TopHealthcareMarketResearchCompaniesSaudiArabia2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesSaudiArabia2026'),
  "TopHealthcareMarketResearchCompaniesSingapore2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesSingapore2026'),
  "TopHealthcareMarketResearchCompaniesSouthKorea2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesSouthKorea2026'),
  "TopHealthcareMarketResearchCompaniesSpain2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesSpain2026'),
  "TopHealthcareMarketResearchCompaniesSweden2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesSweden2026'),
  "TopHealthcareMarketResearchCompaniesSwitzerland2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesSwitzerland2026'),
  "TopHealthcareMarketResearchCompaniesTurkey2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesTurkey2026'),
  "TopHealthcareMarketResearchCompaniesUae2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesUae2026'),
  "TopHealthcareMarketResearchCompaniesUk2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesUk2026'),
  "TopHealthcareMarketResearchCompaniesUsa2026": () => import('@/pages/TopHealthcareMarketResearchCompaniesUsa2026'),
  "TopHematologyMarketResearchCompanies2026": () => import('@/pages/TopHematologyMarketResearchCompanies2026'),
  "TopIndustryMarketResearchListicle": () => import('@/pages/templates/TopIndustryMarketResearchListicle'),
  "TopMarketResearchCompaniesAbuDhabi2026": () => import('@/pages/TopMarketResearchCompaniesAbuDhabi2026'),
  "TopMarketResearchCompaniesArgentina2026": () => import('@/pages/TopMarketResearchCompaniesArgentina2026'),
  "TopMarketResearchCompaniesAustralia2026": () => import('@/pages/TopMarketResearchCompaniesAustralia2026'),
  "TopMarketResearchCompaniesBrazil2026": () => import('@/pages/TopMarketResearchCompaniesBrazil2026'),
  "TopMarketResearchCompaniesCanada2026": () => import('@/pages/TopMarketResearchCompaniesCanada2026'),
  "TopMarketResearchCompaniesChina2026": () => import('@/pages/TopMarketResearchCompaniesChina2026'),
  "TopMarketResearchCompaniesDenmark2026": () => import('@/pages/TopMarketResearchCompaniesDenmark2026'),
  "TopMarketResearchCompaniesDubai2026": () => import('@/pages/TopMarketResearchCompaniesDubai2026'),
  "TopMarketResearchCompaniesEgypt2026": () => import('@/pages/TopMarketResearchCompaniesEgypt2026'),
  "TopMarketResearchCompaniesFrance2026": () => import('@/pages/TopMarketResearchCompaniesFrance2026'),
  "TopMarketResearchCompaniesGcc2026": () => import('@/pages/TopMarketResearchCompaniesGcc2026'),
  "TopMarketResearchCompaniesGermany2026": () => import('@/pages/TopMarketResearchCompaniesGermany2026'),
  "TopMarketResearchCompaniesIndia2026": () => import('@/pages/TopMarketResearchCompaniesIndia2026'),
  "TopMarketResearchCompaniesIreland2026": () => import('@/pages/TopMarketResearchCompaniesIreland2026'),
  "TopMarketResearchCompaniesItaly2026": () => import('@/pages/TopMarketResearchCompaniesItaly2026'),
  "TopMarketResearchCompaniesJapan2026": () => import('@/pages/TopMarketResearchCompaniesJapan2026'),
  "TopMarketResearchCompaniesMalaysia2026": () => import('@/pages/TopMarketResearchCompaniesMalaysia2026'),
  "TopMarketResearchCompaniesNetherlands2026": () => import('@/pages/TopMarketResearchCompaniesNetherlands2026'),
  "TopMarketResearchCompaniesNewZealand2026": () => import('@/pages/TopMarketResearchCompaniesNewZealand2026'),
  "TopMarketResearchCompaniesPoland2026": () => import('@/pages/TopMarketResearchCompaniesPoland2026'),
  "TopMarketResearchCompaniesRiyadh2026": () => import('@/pages/TopMarketResearchCompaniesRiyadh2026'),
  "TopMarketResearchCompaniesSaudiArabia2026": () => import('@/pages/TopMarketResearchCompaniesSaudiArabia2026'),
  "TopMarketResearchCompaniesSingapore2026": () => import('@/pages/TopMarketResearchCompaniesSingapore2026'),
  "TopMarketResearchCompaniesSouthKorea2026": () => import('@/pages/TopMarketResearchCompaniesSouthKorea2026'),
  "TopMarketResearchCompaniesSpain2026": () => import('@/pages/TopMarketResearchCompaniesSpain2026'),
  "TopMarketResearchCompaniesSweden2026": () => import('@/pages/TopMarketResearchCompaniesSweden2026'),
  "TopMarketResearchCompaniesSwitzerland2026": () => import('@/pages/TopMarketResearchCompaniesSwitzerland2026'),
  "TopMarketResearchCompaniesTurkey2026": () => import('@/pages/TopMarketResearchCompaniesTurkey2026'),
  "TopMarketResearchCompaniesUae2026": () => import('@/pages/TopMarketResearchCompaniesUae2026'),
  "TopMarketResearchCompaniesUk2026": () => import('@/pages/TopMarketResearchCompaniesUk2026'),
  "TopMarketResearchCompaniesUsa2026": () => import('@/pages/TopMarketResearchCompaniesUsa2026'),
  "TopOncologyMarketResearchCompanies2026": () => import('@/pages/TopOncologyMarketResearchCompanies2026'),
  "TopPharmaceuticalAnalyticsCompaniesWorldwide2026": () => import('@/pages/TopPharmaceuticalAnalyticsCompaniesWorldwide2026'),
  "TopPharmaMarketResearchCompaniesMiddleEast2026": () => import('@/pages/TopPharmaMarketResearchCompaniesMiddleEast2026'),
  "TurkeyPharmaceuticalMarketResearch": () => import('@/pages/TurkeyPharmaceuticalMarketResearch'),
  "UaeMarketAccessResearch": () => import('@/pages/UaeMarketAccessResearch'),
  "UaePharmaceuticalMarketResearch": () => import('@/pages/UaePharmaceuticalMarketResearch'),
  "UaePricingReimbursementStrategy": () => import('@/pages/UaePricingReimbursementStrategy'),
  "UkPharmaceuticalMarketResearch": () => import('@/pages/UkPharmaceuticalMarketResearch'),
  "UsaPharmaceuticalMarketResearch": () => import('@/pages/UsaPharmaceuticalMarketResearch'),
  "VerifyEmail": () => import('@/pages/VerifyEmail'),
  "VideosIndex": () => import('@/pages/VideosIndex'),
  "WhatIsMarketStudy": () => import('@/pages/WhatIsMarketStudy'),
  "ZhBionixusMarketResearchMiddleEast": () => import('@/pages/ZhBionixusMarketResearchMiddleEast'),
  "ZhStrategicPortfolio": () => import('@/pages/ZhStrategicPortfolio'),
  "ZhTopMarketResearchCompaniesEgypt2026": () => import('@/pages/ZhTopMarketResearchCompaniesEgypt2026'),
  "TopConsumerInsightsCompaniesKsa2026": () => import('@/pages/TopConsumerInsightsCompaniesKsa2026'),
  "TopConsumerInsightsCompaniesSaudiArabiaRedirect": () => import('@/pages/TopConsumerInsightsCompaniesKsa2026'),
};

const seoPathToExport: Record<string, string> = {
  "*": "NotFound",
  "/about": "About",
  "/account-level-market-research": "AccountLevelMarketResearch",
  "/ar/abhath-suq-adwiyah-saudi-arabia": "ArBahthSuqAdwiyahSaudiArabia",
  "/ar/about": "About",
  "/ar/arabic-blog-alsawdyh": "ArabicBlogAlsawdyh",
  "/ar/bionixus-industries": "BionixusIndustries",
  "/ar/blog": "Blog",
  "/ar/contact": "Contact",
  "/ar/healthcare-market-research": "ArHealthcareMarketResearch",
  "/ar/healthcare-market-research/:country": "CountryPage",
  "/ar/healthcare-market-research/saudi-arabia": "ArHealthcareMarketResearchSaudiArabia",
  "/ar/insights": "Insights",
  "/ar/insights/top-sharaket-abhath-alsuq-alimarat-2026": "ArTopMarketResearchCompaniesUae2026",
  "/ar/insights/top-sharaket-abhath-alsuq-alsaudia-2026": "ArTopMarketResearchCompaniesSaudiArabia2026",
  "/ar/insights/top-sharaket-abhath-sihha-alsaudia-2026": "ArTopHealthcareMarketResearchCompaniesSaudiArabia2026",
  "/ar/market-research-healthcare": "MarketResearchHealthcare",
  "/ar/methodology": "Methodology",
  "/ar/services": "Services",
  "/ar/strategic-portfolio": "ConfPortfolio",
  "/ar/strategic-portfolios": "ConfPortfolio",
  "/b2b-industries": "IndustrySegmentPage",
  "/b2c-industries": "IndustrySegmentPage",
  "/bionixus-industries": "BionixusIndustries",
  "/bionixus-industries/insights": "BionixusIndustriesInsights",
  "/bionixus-middle-east-africa": "BionixusMiddleEastAfrica",
  "/bionixus-vs-iqvia-mena": "BionixusVsIqviaMena",
  "/biosimilar-market-entry-saudi-arabia": "BiosimilarMarketEntrySaudiArabia",
  "/blog": "Blog",
  "/brand-tracking-pharma-gcc": "BrandTrackingPharmaGcc",
  "/brazil-healthcare-market-research": "BrazilHealthcareMarketResearch",
  "/brazil-pharmaceutical-market-research": "BrazilPharmaceuticalMarketResearch",
  "/budget-impact-model-saudi-arabia": "BudgetImpactModelSaudiArabia",
  "/case-studies": "CaseStudies",
  "/client-reviews": "ClientReviews",
  "/clinical-diagnostics-market-research": "ClinicalDiagnosticsMarketResearch",
  "/clinical-diagnostics-proposal-request": "ClinicalDiagnosticsProposalRequest",
  "/commercial-effectiveness-pharma-middle-east": "CommercialEffectivenessPharmaMiddleEast",
  "/consumer-market-research": "ConsumerMarketResearchPortal",
  "/contact": "Contact",
  "/cost-effectiveness-analysis-gcc": "CostEffectivenessAnalysisGcc",
  "/cost-effectiveness-analysis-saudi-arabia": "CostEffectivenessAnalysisSaudiArabia",
  "/de/about": "About",
  "/de/bionixus-industries": "BionixusIndustries",
  "/de/blog": "Blog",
  "/de/contact": "Contact",
  "/de/healthcare-market-research/:country": "CountryPage",
  "/de/healthcare-market-research/germany": "DeHealthcareMarketResearchGermany",
  "/de/insights": "Insights",
  "/de/market-research-healthcare": "MarketResearchHealthcare",
  "/de/methodology": "Methodology",
  "/de/services": "Services",
  "/desmoid-tumor-pharma-market-research": "DesmoidTumorPharmaMarketResearch",
  "/diabetes-market-research-uae": "DiabetesMarketResearchUae",
  "/egypt": "CountryPage",
  "/egypt-healthcare-market-research": "HealthcareMarketResearchInEgypt",
  "/egypt-pharmaceutical-market-research": "EgyptPharmaceuticalMarketResearch",
  "/es/about": "About",
  "/es/bionixus-industries": "BionixusIndustries",
  "/es/blog": "Blog",
  "/es/contact": "Contact",
  "/es/healthcare-market-research": "EsHubPage",
  "/es/healthcare-market-research/:country": "CountryPage",
  "/es/healthcare-market-research/spain": "EsHealthcareMarketResearchSpain",
  "/es/insights": "Insights",
  "/es/insights/top-empresas-investigacion-mercado-argentina-2026": "EsTopMarketResearchCompaniesArgentina2026",
  "/es/insights/top-empresas-investigacion-mercado-salud-argentina-2026": "EsTopHealthcareMarketResearchCompaniesArgentina2026",
  "/es/market-research-healthcare": "MarketResearchHealthcare",
  "/es/methodology": "Methodology",
  "/es/services": "Services",
  "/europe": "CountryPage",
  "/faq": "FAQ",
  "/fr/about": "About",
  "/fr/bionixus-industries": "BionixusIndustries",
  "/fr/bionixus-market-research-middle-east": "FrBionixusMarketResearchMiddleEast",
  "/fr/blog": "Blog",
  "/fr/contact": "Contact",
  "/fr/healthcare-market-research": "FrHubPage",
  "/fr/healthcare-market-research/:country": "CountryPage",
  "/fr/healthcare-market-research/france": "FrFranceCountryPage",
  "/fr/insights": "Insights",
  "/fr/market-research-healthcare": "MarketResearchHealthcare",
  "/fr/methodology": "Methodology",
  "/fr/quantitative-healthcare-market-research": "FrQuantitativeHealthcareMarketResearch",
  "/fr/services": "Services",
  "/fr/strategic-portfolio": "FrStrategicPortfolio",
  "/fr/strategic-portfolios": "FrStrategicPortfolio",
  "/gcc-biopharmaceuticals-market": "GccBiopharmaceuticalsMarket",
  "/gcc-clinical-trials-market": "GccClinicalTrialsMarket",
  "/gcc-generic-injectables-market": "GccGenericInjectablesMarket",
  "/gcc-generic-pharmaceuticals-market": "GccGenericPharmaceuticalsMarket",
  "/gcc-hcp-recruitment-market-research": "GccHcpRecruitmentMarketResearch",
  "/gcc-market-access-guide": "GccMarketAccessGuide",
  "/gcc-personalized-medicine-market": "GccPersonalizedMedicineMarket",
  "/gcc-pharma-market-report-2026": "GccPharmaMarketReport2026",
  "/gcc-pharmaceutical-market-research": "GccPharmaceuticalMarketResearch",
  "/gcc-pharmacy-market": "GccPharmacyMarket",
  "/gfk-alternative-egypt": "GfkAlternativeEgypt",
  "/healthcare-fieldwork-gcc": "HealthcareFieldworkGcc",
  "/healthcare-fieldwork-middle-east": "HealthcareFieldworkMiddleEast",
  "/healthcare-market-research": "HubPage",
  "/healthcare-market-research-agency-gcc": "HealthcareMarketResearchAgencyGcc",
  "/healthcare-market-research-argentina": "HealthcareMarketResearchArgentina",
  "/healthcare-market-research-australia": "HealthcareMarketResearchAustralia",
  "/healthcare-market-research-bahrain": "HealthcareMarketResearchInBahrain",
  "/healthcare-market-research-canada": "HealthcareMarketResearchCanada",
  "/healthcare-market-research-china": "HealthcareMarketResearchChina",
  "/healthcare-market-research-companies": "HealthcareMarketResearchCompanies2026",
  "/healthcare-market-research-denmark": "HealthcareMarketResearchDenmark",
  "/healthcare-market-research-france": "HealthcareMarketResearchFrance",
  "/healthcare-market-research-india": "HealthcareMarketResearchIndia",
  "/healthcare-market-research-ireland": "HealthcareMarketResearchIreland",
  "/healthcare-market-research-italy": "HealthcareMarketResearchItaly",
  "/healthcare-market-research-japan": "HealthcareMarketResearchJapan",
  "/healthcare-market-research-jordan": "HealthcareMarketResearchInJordan",
  "/healthcare-market-research-kuwait": "HealthcareMarketResearchInKuwait",
  "/healthcare-market-research-malaysia": "HealthcareMarketResearchMalaysia",
  "/healthcare-market-research-netherlands": "HealthcareMarketResearchNetherlands",
  "/healthcare-market-research-new-zealand": "HealthcareMarketResearchNewZealand",
  "/healthcare-market-research-norway": "HealthcareMarketResearchNorway",
  "/healthcare-market-research-oman": "HealthcareMarketResearchInOman",
  "/healthcare-market-research-poland": "HealthcareMarketResearchPoland",
  "/healthcare-market-research-qatar": "HealthcareMarketResearchInQatar",
  "/healthcare-market-research-singapore": "HealthcareMarketResearchSingapore",
  "/healthcare-market-research-south-korea": "HealthcareMarketResearchSouthKorea",
  "/healthcare-market-research-spain": "HealthcareMarketResearchSpain",
  "/healthcare-market-research-sweden": "HealthcareMarketResearchSweden",
  "/healthcare-market-research-switzerland": "HealthcareMarketResearchSwitzerland",
  "/healthcare-market-research-turkey": "HealthcareMarketResearchTurkey",
  "/healthcare-market-research-uk": "HealthcareMarketResearchUk",
  "/healthcare-market-research-usa": "HealthcareMarketResearchUsa",
  "/healthcare-market-research/:country": "CountryPage",
  "/healthcare-market-research/services/:service": "ServicePage",
  "/healthcare-market-research/therapy/:area": "TherapyPage",
  "/healthcare-market-statistics": "HealthcareMarketStatistics",
  "/heor-consulting": "HeorConsulting",
  "/heor-consulting-saudi-arabia": "HeorConsultingSaudiArabia",
  "/hta-studies-saudi-arabia": "HtaStudiesSaudiArabia",
  "/insights": "Insights",
  "/insights/best-global-market-research-companies-pharma-2026": "BestGlobalMarketResearchCompaniesPharma2026",
  "/insights/best-obesity-weight-management-market-research-firms-2026": "BestObesityWeightManagementMarketResearchFirms2026",
  "/insights/best-rare-disease-market-research-companies-2026": "BestRareDiseaseMarketResearchCompanies2026",
  "/insights/leading-biologics-biosimilars-market-research-companies-2026": "LeadingBiologicsBiosimilarsMarketResearchCompanies2026",
  "/insights/saudi-arabia-biosimilar-market-size-methodology-2026": "SaudiArabiaBiosimilarMarketSizeMethodology2026",
  "/insights/saudi-arabia-cancer-diagnostics-market-size-methodology-2026": "SaudiArabiaCancerDiagnosticsMarketSizeMethodology2026",
  "/insights/saudi-arabia-vaccine-market-size-methodology-2026": "SaudiArabiaVaccineMarketSizeMethodology2026",
  "/insights/top-consumer-healthcare-market-research-firms-2026": "TopConsumerHealthcareMarketResearchFirms2026",
  "/insights/top-consumer-insights-companies-ksa-2026": "TopConsumerInsightsCompaniesKsa2026",
  "/insights/top-consumer-insights-companies-saudi-arabia-2026": "TopConsumerInsightsCompaniesSaudiArabiaRedirect",
  "/insights/top-global-healthcare-market-research-companies-2026": "TopGlobalHealthcareMarketResearchCompanies2026",
  "/insights/top-healthcare-market-research-companies-abu-dhabi-2026": "TopHealthcareMarketResearchCompaniesAbuDhabi2026",
  "/insights/top-healthcare-market-research-companies-argentina-2026": "TopHealthcareMarketResearchCompaniesArgentina2026",
  "/insights/top-healthcare-market-research-companies-australia-2026": "TopHealthcareMarketResearchCompaniesAustralia2026",
  "/insights/top-healthcare-market-research-companies-brazil-2026": "TopHealthcareMarketResearchCompaniesBrazil2026",
  "/insights/top-healthcare-market-research-companies-canada-2026": "TopHealthcareMarketResearchCompaniesCanada2026",
  "/insights/top-healthcare-market-research-companies-china-2026": "TopHealthcareMarketResearchCompaniesChina2026",
  "/insights/top-healthcare-market-research-companies-denmark-2026": "TopHealthcareMarketResearchCompaniesDenmark2026",
  "/insights/top-healthcare-market-research-companies-dubai-2026": "TopHealthcareMarketResearchCompaniesDubai2026",
  "/insights/top-healthcare-market-research-companies-europe-2026": "TopHealthcareMarketResearchCompaniesEurope2026",
  "/insights/top-healthcare-market-research-companies-france-2026": "TopHealthcareMarketResearchCompaniesFrance2026",
  "/insights/top-healthcare-market-research-companies-germany-2026": "TopHealthcareMarketResearchCompaniesGermany2026",
  "/insights/top-healthcare-market-research-companies-india-2026": "TopHealthcareMarketResearchCompaniesIndia2026",
  "/insights/top-healthcare-market-research-companies-ireland-2026": "TopHealthcareMarketResearchCompaniesIreland2026",
  "/insights/top-healthcare-market-research-companies-italy-2026": "TopHealthcareMarketResearchCompaniesItaly2026",
  "/insights/top-healthcare-market-research-companies-japan-2026": "TopHealthcareMarketResearchCompaniesJapan2026",
  "/insights/top-healthcare-market-research-companies-kuwait-2026": "TopHealthcareMarketResearchCompaniesKuwait2026",
  "/insights/top-healthcare-market-research-companies-malaysia-2026": "TopHealthcareMarketResearchCompaniesMalaysia2026",
  "/insights/top-healthcare-market-research-companies-mena-2026": "TopHealthcareMarketResearchCompaniesMena2026",
  "/insights/top-healthcare-market-research-companies-netherlands-2026": "TopHealthcareMarketResearchCompaniesNetherlands2026",
  "/insights/top-healthcare-market-research-companies-new-zealand-2026": "TopHealthcareMarketResearchCompaniesNewZealand2026",
  "/insights/top-healthcare-market-research-companies-norway-2026": "TopHealthcareMarketResearchCompaniesNorway2026",
  "/insights/top-healthcare-market-research-companies-poland-2026": "TopHealthcareMarketResearchCompaniesPoland2026",
  "/insights/top-healthcare-market-research-companies-riyadh-2026": "TopHealthcareMarketResearchCompaniesRiyadh2026",
  "/insights/top-healthcare-market-research-companies-saudi-arabia-2026": "TopHealthcareMarketResearchCompaniesSaudiArabia2026",
  "/insights/top-healthcare-market-research-companies-singapore-2026": "TopHealthcareMarketResearchCompaniesSingapore2026",
  "/insights/top-healthcare-market-research-companies-south-korea-2026": "TopHealthcareMarketResearchCompaniesSouthKorea2026",
  "/insights/top-healthcare-market-research-companies-spain-2026": "TopHealthcareMarketResearchCompaniesSpain2026",
  "/insights/top-healthcare-market-research-companies-sweden-2026": "TopHealthcareMarketResearchCompaniesSweden2026",
  "/insights/top-healthcare-market-research-companies-switzerland-2026": "TopHealthcareMarketResearchCompaniesSwitzerland2026",
  "/insights/top-healthcare-market-research-companies-turkey-2026": "TopHealthcareMarketResearchCompaniesTurkey2026",
  "/insights/top-healthcare-market-research-companies-uae-2026": "TopHealthcareMarketResearchCompaniesUae2026",
  "/insights/top-healthcare-market-research-companies-uk-2026": "TopHealthcareMarketResearchCompaniesUk2026",
  "/insights/top-healthcare-market-research-companies-usa-2026": "TopHealthcareMarketResearchCompaniesUsa2026",
  "/insights/top-hematology-market-research-companies-2026": "TopHematologyMarketResearchCompanies2026",
  "/insights/top-market-research-companies-abu-dhabi-2026": "TopMarketResearchCompaniesAbuDhabi2026",
  "/insights/top-market-research-companies-argentina-2026": "TopMarketResearchCompaniesArgentina2026",
  "/insights/top-market-research-companies-australia-2026": "TopMarketResearchCompaniesAustralia2026",
  "/insights/top-market-research-companies-brazil-2026": "TopMarketResearchCompaniesBrazil2026",
  "/insights/top-market-research-companies-canada-2026": "TopMarketResearchCompaniesCanada2026",
  "/insights/top-market-research-companies-china-2026": "TopMarketResearchCompaniesChina2026",
  "/insights/top-market-research-companies-denmark-2026": "TopMarketResearchCompaniesDenmark2026",
  "/insights/top-market-research-companies-dubai-2026": "TopMarketResearchCompaniesDubai2026",
  "/insights/top-market-research-companies-egypt-2026": "TopMarketResearchCompaniesEgypt2026",
  "/insights/top-market-research-companies-france-2026": "TopMarketResearchCompaniesFrance2026",
  "/insights/top-market-research-companies-gcc-2026": "TopMarketResearchCompaniesGcc2026",
  "/insights/top-market-research-companies-germany-2026": "TopMarketResearchCompaniesGermany2026",
  "/insights/top-market-research-companies-india-2026": "TopMarketResearchCompaniesIndia2026",
  "/insights/top-market-research-companies-ireland-2026": "TopMarketResearchCompaniesIreland2026",
  "/insights/top-market-research-companies-italy-2026": "TopMarketResearchCompaniesItaly2026",
  "/insights/top-market-research-companies-japan-2026": "TopMarketResearchCompaniesJapan2026",
  "/insights/top-market-research-companies-malaysia-2026": "TopMarketResearchCompaniesMalaysia2026",
  "/insights/top-market-research-companies-netherlands-2026": "TopMarketResearchCompaniesNetherlands2026",
  "/insights/top-market-research-companies-new-zealand-2026": "TopMarketResearchCompaniesNewZealand2026",
  "/insights/top-market-research-companies-poland-2026": "TopMarketResearchCompaniesPoland2026",
  "/insights/top-market-research-companies-riyadh-2026": "TopMarketResearchCompaniesRiyadh2026",
  "/insights/top-market-research-companies-saudi-arabia-2026": "TopMarketResearchCompaniesSaudiArabia2026",
  "/insights/top-market-research-companies-singapore-2026": "TopMarketResearchCompaniesSingapore2026",
  "/insights/top-market-research-companies-south-korea-2026": "TopMarketResearchCompaniesSouthKorea2026",
  "/insights/top-market-research-companies-spain-2026": "TopMarketResearchCompaniesSpain2026",
  "/insights/top-market-research-companies-sweden-2026": "TopMarketResearchCompaniesSweden2026",
  "/insights/top-market-research-companies-switzerland-2026": "TopMarketResearchCompaniesSwitzerland2026",
  "/insights/top-market-research-companies-turkey-2026": "TopMarketResearchCompaniesTurkey2026",
  "/insights/top-market-research-companies-uae-2026": "TopMarketResearchCompaniesUae2026",
  "/insights/top-market-research-companies-uk-2026": "TopMarketResearchCompaniesUk2026",
  "/insights/top-market-research-companies-usa-2026": "TopMarketResearchCompaniesUsa2026",
  "/insights/top-oncology-market-research-companies-2026": "TopOncologyMarketResearchCompanies2026",
  "/insights/top-pharma-market-research-companies-middle-east-2026": "TopPharmaMarketResearchCompaniesMiddleEast2026",
  "/insights/top-pharmaceutical-analytics-companies-worldwide-2026": "TopPharmaceuticalAnalyticsCompaniesWorldwide2026",
  "/iqvia-alternative": "IqviaAlternative",
  "/kantar-health-alternative-gcc": "KantarHealthAlternativeGcc",
  "/kol-mapping-saudi-arabia-oncology": "KolMappingSaudiArabiaOncology",
  "/kuwait": "CountryPage",
  "/kuwait-market-access-research": "KuwaitMarketAccessResearch",
  "/market-access": "MarketAccess",
  "/market-reports": "HealthcareReportsHub",
  "/market-reports/country/:marketSlug": "HealthcareReportsByCountry",
  "/market-reports/therapy/:therapyAreaSlug": "HealthcareReportsByTherapy",
  "/market-research": "MarketResearch",
  "/market-research-bahrain": "MarketResearchBahrain",
  "/market-research-by-industry": "MarketResearchByIndustry",
  "/market-research-egypt": "MarketResearchEgypt",
  "/market-research-gcc": "MarketResearchGcc",
  "/market-research-healthcare": "MarketResearchHealthcare",
  "/market-research-home": "MarketResearchHome",
  "/market-research-in-egypt": "MarketResearchInEgypt",
  "/market-research-in-saudi-arabia": "MarketResearchInSaudiArabia",
  "/market-research-in-uae": "MarketResearchInUae",
  "/market-research-ksa": "MarketResearchKsa",
  "/market-research-kuwait": "MarketResearchKuwait",
  "/market-research-oman": "MarketResearchOman",
  "/market-research-qatar": "MarketResearchQatar",
  "/market-research-saudi": "MarketResearchSaudi",
  "/market-research-saudi-arabia-pharmaceutical": "MarketResearchSaudiArabiaPharmaceutical",
  "/market-research-uae": "MarketResearchUae",
  "/market-research/:industrySlug": "IndustryGlobalHubPage",
  "/market-study": "WhatIsMarketStudy",
  "/media": "Media",
  "/medical-affairs-insight-research-gcc": "MedicalAffairsInsightResearchGcc",
  "/mena-pharma-market-data": "MenaMarketData",
  "/methodology": "Methodology",
  "/msl-insight-research-middle-east": "MslInsightResearchMiddleEast",
  "/new-home": "PremiumHomePreview",
  "/news": "NewsHub",
  "/nf1-pharma-market-research": "Nf1PharmaMarketResearch",
  "/nielsen-alternative": "NielsenAlternative",
  "/patient-adherence-research-middle-east": "PatientAdherenceResearchMiddleEast",
  "/patient-journey-research-gcc": "PatientJourneyResearchGcc",
  "/patient-support-program-research-gcc": "PatientSupportProgramResearchGcc",
  "/pharma-fieldwork-egypt": "PharmaFieldworkEgypt",
  "/pharma-fieldwork-saudi-arabia": "PharmaFieldworkSaudiArabia",
  "/pharma-fieldwork-uae": "PharmaFieldworkUae",
  "/pharma-healthcare-industries": "IndustrySegmentPage",
  "/pharmaceutical-market-research-argentina": "ArgentinaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-australia": "AustraliaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-bahrain": "BahrainPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-canada": "CanadaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-china": "ChinaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-denmark": "DenmarkPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-dubai": "PharmaceuticalMarketResearchDubai",
  "/pharmaceutical-market-research-france": "FrancePharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-germany": "GermanyPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-india": "IndiaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-ireland": "IrelandPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-italy": "ItalyPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-japan": "JapanPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-jordan": "JordanPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-kuwait": "KuwaitPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-malaysia": "MalaysiaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-netherlands": "NetherlandsPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-new-zealand": "NewZealandPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-oman": "OmanPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-poland": "PolandPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-provider": "PharmaceuticalMarketResearchProvider",
  "/pharmaceutical-market-research-qatar": "QatarPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-singapore": "SingaporePharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-south-korea": "SouthKoreaPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-spain": "SpainPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-sweden": "SwedenPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-switzerland": "SwitzerlandPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-turkey": "TurkeyPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-uk": "UkPharmaceuticalMarketResearch",
  "/pharmaceutical-market-research-usa": "UsaPharmaceuticalMarketResearch",
  "/pharmaceutical-therapy-areas": "PharmaceuticalTherapyAreas",
  "/pharmacies-saudi-arabia-marketing": "PharmaciesSaudiArabiaMarketing",
  "/physician-survey-saudi-arabia": "PhysicianSurveySaudiArabia",
  "/premium-home-preview": "PremiumHomePreview",
  "/pricing": "Pricing",
  "/privacy": "Privacy",
  "/pt/about": "About",
  "/pt/bionixus-industries": "BionixusIndustries",
  "/pt/blog": "Blog",
  "/pt/contact": "Contact",
  "/pt/insights": "Insights",
  "/pt/insights/top-empresas-pesquisa-mercado-brasil-2026": "PtTopEmpresasPesquisaMercadoBrasil2026",
  "/pt/insights/top-empresas-pesquisa-mercado-saude-brasil-2026": "PtTopHealthcareMarketResearchCompaniesBrazil2026",
  "/pt/insights/top-market-research-companies-brasil-2026": "PtTopMarketResearchCompaniesBrazil2026",
  "/pt/market-research-healthcare": "MarketResearchHealthcare",
  "/pt/methodology": "Methodology",
  "/pt/pesquisa-mercado-farmaceutico-brasil": "PtBrazilPharmaceuticalMarketResearch",
  "/pt/pesquisa-mercado-saude-brasil": "PtBrazilHealthcareMarketResearch",
  "/pt/services": "Services",
  "/qatar-market-access-research": "QatarMarketAccessResearch",
  "/qualitative-market-research": "QualitativeMarketResearch",
  "/quantitative-healthcare-market-research": "QuantitativeHealthcareMarketResearchGuide",
  "/real-world-data-healthcare-middle-east": "RealWorldDataHealthcareMiddleEast",
  "/real-world-evidence": "RealWorldEvidence",
  "/real-world-evidence-gcc": "RealWorldEvidenceGcc",
  "/resources": "Resources",
  "/respiratory-market-access-gcc": "RespiratoryMarketAccessGcc",
  "/ru/about": "About",
  "/ru/bionixus-industries": "BionixusIndustries",
  "/ru/blog": "Blog",
  "/ru/contact": "Contact",
  "/ru/healthcare-market-research": "HubPage",
  "/ru/insights": "Insights",
  "/ru/market-research-healthcare": "MarketResearchHealthcare",
  "/ru/methodology": "Methodology",
  "/ru/services": "Services",
  "/saudi-arabia": "CountryPage",
  "/saudi-payer-market-access-research": "SaudiPayerMarketAccessResearch",
  "/services": "Services",
  "/services/:slug": "ServiceDetail",
  "/services/cross-industry": "CrossIndustryMarketResearch",
  "/sfda-market-access-strategy-saudi-arabia": "SfdaMarketAccessStrategySaudiArabia",
  "/sitemap": "SiteMapPage",
  "/specialist-physician-panel-uae": "SpecialistPhysicianPanelUae",
  "/strategic-portfolio": "ConfPortfolio",
  "/strategic-portfolios": "ConfPortfolio",
  "/templates/country-research-brief": "CountryResearchBriefTemplate",
  "/templates/mystery-shop-retail-brief": "MysteryShopRetailBrief",
  "/terms": "Terms",
  "/tools/syndicated-data-gap": "SyndicatedDataGapTool",
  "/uae": "CountryPage",
  "/uae-market-access-research": "UaeMarketAccessResearch",
  "/uae-pharmaceutical-market-research": "UaePharmaceuticalMarketResearch",
  "/uae-pricing-reimbursement-strategy": "UaePricingReimbursementStrategy",
  "/uk": "CountryPage",
  "/verify-email": "VerifyEmail",
  "/videos": "VideosIndex",
  "/zh/about": "About",
  "/zh/bionixus-industries": "BionixusIndustries",
  "/zh/bionixus-market-research-middle-east": "ZhBionixusMarketResearchMiddleEast",
  "/zh/blog": "Blog",
  "/zh/contact": "Contact",
  "/zh/healthcare-market-research": "HubPage",
  "/zh/insights": "Insights",
  "/zh/insights/top-market-research-companies-egypt-2026": "ZhTopMarketResearchCompaniesEgypt2026",
  "/zh/market-research-healthcare": "MarketResearchHealthcare",
  "/zh/methodology": "Methodology",
  "/zh/services": "Services",
  "/zh/strategic-portfolio": "ZhStrategicPortfolio",
  "/zh/strategic-portfolios": "ZhStrategicPortfolio",
};

export function getSeoPageLoader(pathname: string): (() => Promise<unknown>) | undefined {
  const normalized = pathname.replace(/\/$/, '') || '/';
  const exportName = seoPathToExport[normalized] ?? seoPathToExport[pathname];
  return exportName ? seoPageLoaders[exportName] : undefined;
}
