import { CountryCompaniesGuide, type CountryCompaniesGuideConfig } from '@/components/seo/CountryCompaniesGuide';

const config: CountryCompaniesGuideConfig = {
  path: '/pharmaceutical-companies-india',
  countryName: 'India',
  industry: 'pharmaceutical',
  title: 'Top 20 Pharmaceutical Companies in India (2026 Ranked List)',
  metaDescription:
    'Top 20 pharmaceutical companies in India ranked for 2026 — Sun Pharma, Cipla, Dr. Reddy\'s, Lupin, CDSCO regulation, exports and market size. By BioNixus.',
  h1: 'Pharmaceutical Companies in India',
  introLead: 'Pharmaceutical companies in India form the "pharmacy of the world" — the largest generic medicine supplier globally',
  introRest: 'This guide ranks Sun Pharma, Cipla, Dr. Reddy\'s and the other majors, covers CDSCO regulation, the domestic market of roughly $48–55 billion, and India\'s $27B+ export machine.',
  stats: [
    { value: '~$48–55B', label: 'Domestic pharma market 2026' },
    { value: '~$27B+', label: 'Annual pharma exports' },
    { value: '#1', label: 'Global generics supplier by volume' },
    { value: '~20%', label: 'Of global generic supply' },
  ],
  quickAnswer: {
    marketSize: 'approximately USD 48–55 billion domestically, with USD 27+ billion in exports',
    growthRate: '~9–10% YoY',
    regulatorLabel: 'CDSCO (Central Drugs Standard Control Organisation)',
    extraSentence: 'India supplies ~20% of global generic volume and ~60% of global vaccine doses — every global sourcing, pricing, and market-entry strategy touches India.',
  },
  marketOverviewParagraphs: [
    'India is the world\'s third-largest pharmaceutical market by volume and around eleventh by value, with a domestic market of approximately US$48–55 billion in 2026 growing 9–10% annually. Indian manufacturers supply roughly 20% of global generic medicines and about 60% of global vaccine doses.',
    'CDSCO (Central Drugs Standard Control Organisation) under the Drugs Controller General of India (DCGI) regulates approvals, with state FDAs handling manufacturing licences. The NPPA (National Pharmaceutical Pricing Authority) caps prices of essential medicines under the DPCO, while the trade-generics and branded-generics channels drive intense retail competition.',
    'Sun Pharmaceutical is India\'s largest company and the world\'s fourth-largest specialty generics player. Cipla, Dr. Reddy\'s, Lupin, Zydus, Aurobindo, Torrent, Mankind, Alkem, and Glenmark round out a top tier with deep US ANDA portfolios and growing specialty/biosimilar ambitions. The PLI (Production Linked Incentive) scheme is rebuilding API self-sufficiency after decades of China dependence.',
  ],
  companies: [
    { name: 'Sun Pharmaceutical Industries', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Specialty, dermatology, ophthalmics, generics', notes: 'India\'s largest pharma; global specialty generics leader' },
    { name: 'Cipla', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Respiratory, HIV, generics', notes: 'Global respiratory and access-medicine pioneer' },
    { name: 'Dr. Reddy\'s Laboratories', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Generics, biosimilars, oncology', notes: 'Major US generics + biosimilar portfolio' },
    { name: 'Lupin', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Cardiovascular, diabetes, respiratory', notes: 'Top-10 global generics company' },
    { name: 'Zydus Lifesciences', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Generics, biologics, vaccines', notes: 'Broad portfolio incl. biologics and vaccines' },
    { name: 'Aurobindo Pharma', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Generics, injectables, ARVs', notes: 'One of the largest US generic suppliers by volume' },
    { name: 'Torrent Pharmaceuticals', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Cardiovascular, CNS, branded generics', notes: 'Strong branded-generics franchise' },
    { name: 'Mankind Pharma', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Branded generics, OTC, consumer', notes: 'Deep rural/tier-2 retail penetration' },
    { name: 'Alkem Laboratories', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Anti-infectives, GI, branded generics', notes: 'Leader in anti-infective prescriptions' },
    { name: 'Glenmark Pharmaceuticals', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Dermatology, respiratory, oncology', notes: 'Innovation-led with novel pipeline' },
    { name: 'Intas Pharmaceuticals', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Biosimilars, CNS, oncology', notes: 'Biosimilar leader via Accord Healthcare' },
    { name: 'Serum Institute of India', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Vaccines', notes: 'World\'s largest vaccine manufacturer by doses' },
    { name: 'Biocon', hq: 'India', type: 'Local Manufacturer', therapeuticAreas: 'Biosimilars, insulin, oncology', notes: 'Global biosimilars via Biocon Biologics' },
    { name: 'Pfizer India', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Vaccines, oncology, hospital', notes: 'Listed Indian subsidiary' },
    { name: 'GSK India', hq: 'UK', type: 'MNC Office', therapeuticAreas: 'Vaccines, dermatology, anti-infectives', notes: 'Long-established listed subsidiary' },
    { name: 'Novartis India', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, cardiovascular', notes: 'Innovator portfolio; patent-litigation history' },
    { name: 'AstraZeneca India', hq: 'UK / Sweden', type: 'MNC Office', therapeuticAreas: 'Oncology, CVRM, respiratory', notes: 'Fast-growing oncology franchise' },
    { name: 'Sanofi India', hq: 'France', type: 'MNC Office', therapeuticAreas: 'Diabetes, vaccines, consumer', notes: 'Insulin and vaccine presence' },
    { name: 'Abbott India', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Branded generics, women\'s health, GI', notes: 'Largest MNC by Indian branded-generic sales' },
    { name: 'McKesson-style national wholesalers (AIOCD network)', hq: 'India', type: 'Distributor', therapeuticAreas: 'Wholesale & retail distribution', notes: '~650,000 retail pharmacies via layered stockist network' },
  ],
  categoryBlurbs: {
    local: 'Indian manufacturers dominate: Sun, Cipla, Dr. Reddy\'s, Lupin, Zydus, Aurobindo, Torrent, Mankind, Alkem, Glenmark, Intas, Serum Institute, and Biocon together run hundreds of FDA/EMA-approved plants.',
    mnc: 'MNCs operate listed subsidiaries focused on vaccines, oncology, and branded portfolios — Abbott is the largest MNC in Indian retail pharma.',
    regional: 'The market is largely domestic + global MNC; regional MENA/Asian players have limited share.',
    distributor: 'Distribution flows through a layered C&F agent → stockist → retailer network reaching ~650,000 pharmacies, coordinated under AIOCD trade structures.',
  },
  regulator: {
    short: 'CDSCO',
    full: 'Central Drugs Standard Control Organisation',
    registrationTimeline: '9–18 months (new drugs); state licences for generics',
    renewalPeriod: '5 years (import licences)',
    pricingModel: 'NPPA/DPCO ceiling prices on essential medicines; trade margins capped on select devices/drugs',
    requirements: [
      'New drug approval via CDSCO/DCGI (CTD format)',
      'Import licence (Form 10) with local authorised agent',
      'State FDA manufacturing licences for local production',
      'CDSCO clinical trial waiver possible for approved-elsewhere drugs',
      'NPPA pricing compliance for scheduled formulations',
      'Local subsidiary or agent required for imports',
    ],
    note: 'India rewards scale and cost leadership. For innovators, the commercial channels are metro private hospitals, oncology centres, and the growing insurance sector (Ayushman Bharat covers 500M+ lives for hospitalisation). For generic players, India is both a competitor benchmark and a sourcing base.',
  },
  growthDrivers: [
    { title: 'Ayushman Bharat & Insurance Expansion', desc: 'The world\'s largest public health insurance scheme plus fast-growing private insurance expand treated-patient volume.' },
    { title: 'PLI & API Self-Sufficiency', desc: 'Production Linked Incentive schemes are rebuilding domestic API capacity and attracting global supply-chain diversification.' },
    { title: 'Biosimilars & Specialty Shift', desc: 'Indian majors are moving up the value chain into biosimilars, complex generics, and novel specialty assets.' },
    { title: 'Chronic Disease Burden', desc: 'World\'s largest diabetes population (~101M) and rising cardiovascular/oncology burden drive chronic-therapy volume.' },
    { title: 'Export Machine', desc: 'US$27B+ exports to 200+ countries; US generics, Africa ARVs, and global vaccines keep manufacturing investment high.' },
    { title: 'Hospital & Diagnostics Boom', desc: 'Private hospital chains (Apollo, Fortis, Max, Manipal) and diagnostics networks expand specialty drug channels.' },
  ],
  bionixusServices: [
    { title: 'Physician Surveys & KOL Mapping', desc: 'Quantitative and qualitative fieldwork with Indian physicians across metro tertiary, tier-2, and government hospital segments.' },
    { title: 'Market Access & Pricing Strategy', desc: 'CDSCO pathway analysis, NPPA/DPCO pricing exposure assessment, and hospital formulary intelligence.' },
    { title: 'Competitive & Sourcing Intelligence', desc: 'Tracking Indian competitor pipelines, API sourcing dynamics, and export registration footprints.' },
    { title: 'India vs GCC/Global Benchmarking', desc: 'Comparative launch sequencing for companies weighing India against GCC, MENA, and Southeast Asian markets.' },
  ],
  faq: [
    { q: 'What are the top 10 pharmaceutical companies in India?', a: 'By revenue, the top Indian pharmaceutical companies in 2026 are Sun Pharmaceutical, Cipla, Dr. Reddy\'s Laboratories, Lupin, Zydus Lifesciences, Aurobindo Pharma, Torrent Pharmaceuticals, Mankind Pharma, Alkem Laboratories, and Glenmark — with Intas, Biocon, and Serum Institute major unlisted/specialty players.' },
    { q: 'What is the size of India\'s pharmaceutical market?', a: 'India\'s domestic pharmaceutical market is approximately US$48–55 billion in 2026, growing 9–10% annually, with exports adding US$27+ billion. India is the world\'s third-largest market by volume and supplies ~20% of global generics.' },
    { q: 'Who regulates pharmaceuticals in India?', a: 'CDSCO (Central Drugs Standard Control Organisation), headed by the Drugs Controller General of India (DCGI), approves new drugs, imports, and clinical trials. State FDAs license manufacturing. The NPPA controls prices of essential medicines under the DPCO.' },
    { q: 'Why is India called the pharmacy of the world?', a: 'India supplies around 20% of global generic medicine volume and roughly 60% of global vaccine doses. The Serum Institute of India is the world\'s largest vaccine producer, and Indian ARVs supply most of Africa\'s HIV programmes.' },
    { q: 'How do foreign pharma companies enter the Indian market?', a: 'Options include a wholly-owned subsidiary (100% FDI permitted in greenfield pharma), licensing to an Indian partner, or import via an authorised agent holding a Form 10 import licence. New drugs approved in reference markets can often obtain clinical-trial waivers, shortening CDSCO timelines to 9–18 months.' },
    { q: 'What is the biggest commercial risk in Indian pharma?', a: 'Price control: the NPPA caps prices of medicines on the National List of Essential Medicines and has occasionally imposed extraordinary caps (e.g. cardiac stents). Intense branded-generic competition — over 3,000 manufacturers — also compresses margins outside patented specialty niches.' },
  ],
  relatedLinks: [
    { to: '/india-healthcare-market-report', label: 'India healthcare market report 2026' },
    { to: '/india-medical-devices-market-report', label: 'India medical devices market report' },
    { to: '/pharmaceutical-companies-china', label: 'Pharmaceutical companies in China' },
    { to: '/pharmaceutical-companies-singapore', label: 'Pharmaceutical companies in Singapore' },
    { to: '/pharmaceutical-companies-usa', label: 'Pharmaceutical companies in USA' },
    { to: '/gcc-market-access-guide', label: 'GCC market access guide 2026' },
  ],
  sources: [
    'CDSCO — Central Drugs Standard Control Organisation',
    'Pharmexcil export statistics',
    'NPPA/DPCO pricing notifications',
    'Company filings (NSE/BSE-listed manufacturers)',
    'BioNixus proprietary research (India & Asia, 2024–2026)',
  ],
  publishedDate: '2026-08-22',
  modifiedDate: '2026-08-22',
  conversion: {
    routingHint: 'Mention CDSCO pathways, NPPA pricing, or India sourcing priorities for a faster routed response.',
    emailSubject: 'India pharma market research — BioNixus',
  },
};

const IndiaPharmaCompanies = () => <CountryCompaniesGuide config={config} />;

export default IndiaPharmaCompanies;
