import { CountryCompaniesGuide, type CountryCompaniesGuideConfig } from '@/components/seo/CountryCompaniesGuide';

const config: CountryCompaniesGuideConfig = {
  path: '/pharmaceutical-companies-jordan',
  countryName: 'Jordan',
  industry: 'pharmaceutical',
  title: 'Top Pharmaceutical Companies in Jordan (2026 Ranked List)',
  metaDescription:
    'Top pharmaceutical companies in Jordan ranked for 2026 — Hikma, Dar Al Dawa, MidPharma, JFDA regulation, export industry and market size. Research by BioNixus.',
  h1: 'Pharmaceutical Companies in Jordan',
  introLead: 'Pharmaceutical companies in Jordan anchor one of the MENA region\'s most successful pharma export industries',
  introRest: 'This guide covers Hikma and the other major Jordanian manufacturers, MNC offices, the JFDA regulatory framework, and a domestic market of roughly $1.4–1.8 billion supporting an export industry reaching 60+ countries.',
  stats: [
    { value: '~$1.4–1.8B', label: 'Domestic pharma market 2026' },
    { value: '~$1B+', label: 'Annual pharma exports' },
    { value: '~11.5M', label: 'Population' },
    { value: '12–24 mo', label: 'JFDA registration timeline' },
  ],
  quickAnswer: {
    marketSize: 'approximately USD 1.4–1.8 billion domestically, with $1B+ in annual exports',
    growthRate: '~6% YoY',
    regulatorLabel: 'the Jordan Food and Drug Administration (JFDA)',
    extraSentence: 'Jordan punches far above its weight — Hikma is MENA\'s largest home-grown pharma multinational, and Jordanian generics are registered across the GCC, Iraq, and Africa.',
  },
  marketOverviewParagraphs: [
    'Jordan\'s pharmaceutical sector combines a modest domestic market (~US$1.4–1.8 billion, 11.5 million population) with a globally significant export industry. Pharmaceutical products are among Jordan\'s top merchandise exports, shipped to more than 60 markets across the GCC, Iraq, North Africa, Europe, and the USA.',
    'The JFDA (Jordan Food and Drug Administration) is regarded as one of the region\'s most rigorous regulators, and JFDA approval is often used as a reference by other Arab regulatory authorities. Registration typically takes 12–24 months with full CTD requirements.',
    'Hikma Pharmaceuticals — founded in Amman in 1978 and now FTSE-100 listed — is the flagship, with major injectables, generics, and branded businesses across MENA and the USA. Dar Al Dawa, MidPharma, Hayat Pharma, and the Arab Pharmaceutical Manufacturing company round out a manufacturing cluster concentrated around Amman and Sahab.',
  ],
  companies: [
    { name: 'Hikma Pharmaceuticals', hq: 'Jordan / UK', type: 'Local Manufacturer', therapeuticAreas: 'Injectables, generics, branded generics', notes: 'MENA\'s largest home-grown pharma MNC; FTSE-100; major US injectables business' },
    { name: 'Dar Al Dawa (DAD)', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Branded generics, antibiotics, dermatology', notes: 'Second-largest Jordanian manufacturer; strong Iraq/GCC exports' },
    { name: 'MidPharma (Middle East Pharmaceutical & Chemical Industries)', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Generics, CNS, cardiovascular', notes: 'EU-GMP certified; European export capability' },
    { name: 'The Arab Pharmaceutical Manufacturing Co. (APM)', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Generics, OTC', notes: 'One of Jordan\'s oldest manufacturers (est. 1962)' },
    { name: 'Hayat Pharmaceutical Industries', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Generics, cardiovascular, diabetes', notes: 'Amman-listed; regional export growth' },
    { name: 'Jordan River Pharmaceutical Industries', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Generics, penems, oncology', notes: 'Specialty and hospital injectables' },
    { name: 'Pharma International (PIC)', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Generics, semisolids, liquids', notes: 'Strong Iraq and Gulf registrations' },
    { name: 'Amman Pharmaceutical Industries (API)', hq: 'Jordan', type: 'Local Manufacturer', therapeuticAreas: 'Dermatology, ophthalmics', notes: 'Niche dermatology/ophthalmic specialist' },
    { name: 'Pfizer', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Oncology, vaccines, inflammation', notes: 'Scientific office serving Jordan and Levant' },
    { name: 'Novartis', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, immunology, cardiovascular', notes: 'Levant cluster office' },
    { name: 'Roche', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, haematology', notes: 'Oncology supplier to Royal Medical Services and MOH' },
    { name: 'Sanofi', hq: 'France', type: 'MNC Office', therapeuticAreas: 'Diabetes, vaccines, rare disease', notes: 'Established Levant presence' },
    { name: 'MSD', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Oncology, vaccines', notes: 'Keytruda and vaccines via Jordan office' },
    { name: 'AstraZeneca', hq: 'UK / Sweden', type: 'MNC Office', therapeuticAreas: 'Oncology, respiratory, CVRM', notes: 'Growing Levant oncology franchise' },
    { name: 'Julphar', hq: 'UAE', type: 'Regional', therapeuticAreas: 'Generics, consumer health', notes: 'Gulf generics supplier to Jordanian market' },
    { name: 'SPIMACO', hq: 'Saudi Arabia', type: 'Regional', therapeuticAreas: 'Generics, OTC', notes: 'Saudi manufacturer active in Jordan' },
    { name: 'Drug Store chains / Al-Hikma Drugstore', hq: 'Jordan', type: 'Distributor', therapeuticAreas: 'Wholesale & retail distribution', notes: 'National wholesale network serving ~2,900 pharmacies' },
    { name: 'United Pharmaceuticals (distribution arm)', hq: 'Jordan', type: 'Distributor', therapeuticAreas: 'Import & hospital distribution', notes: 'Key MOH/JPD tender participant' },
  ],
  categoryBlurbs: {
    local: 'Jordan\'s manufacturing cluster — Hikma, Dar Al Dawa, MidPharma, APM, Hayat, Jordan River, PIC, and API — is export-oriented, with several EU-GMP and US FDA-approved facilities around Amman and Sahab.',
    mnc: 'Multinationals serve Jordan through scientific offices, often covering the wider Levant. Innovator products reach patients via MOH, Royal Medical Services, and private hospital channels.',
    regional: 'Gulf manufacturers such as Julphar and SPIMACO compete in the Jordanian generics and OTC segments.',
    distributor: 'A concentrated wholesale layer distributes to roughly 2,900 retail pharmacies and participates in Joint Procurement Department (JPD) and MOH tenders.',
  },
  regulator: {
    short: 'JFDA',
    full: 'Jordan Food and Drug Administration',
    registrationTimeline: '12–24 months',
    renewalPeriod: '5 years',
    pricingModel: 'External reference pricing (origin country + regional basket); among the region\'s strictest pricing reviews',
    requirements: [
      'Full CTD dossier with certificates of analysis',
      'GMP certificate; JFDA may inspect foreign sites',
      'Certificate of Pharmaceutical Product (CPP)',
      'Arabic labelling and leaflet',
      'Local agent / marketing authorisation holder required',
      'Pricing approval before marketing',
    ],
    note: 'JFDA approval carries reference weight across Arab markets, which is why many manufacturers register in Jordan early even though the domestic market is small. Public procurement flows through the Joint Procurement Department (JPD), MOH, and Royal Medical Services tenders.',
  },
  growthDrivers: [
    { title: 'Export Engine', desc: 'Pharma is a top-3 Jordanian export sector; GCC, Iraq, and African registrations keep manufacturing utilisation and investment high.' },
    { title: 'Regulatory Reputation', desc: 'JFDA\'s rigour makes Jordan a reference market — approval accelerates registrations across the Arab world.' },
    { title: 'Medical & Health Tourism', desc: 'Amman is a regional medical tourism destination, supporting private hospital pharmaceutical demand.' },
    { title: 'Biosimilar Ambitions', desc: 'Jordanian manufacturers are moving up the value chain into biosimilars and complex generics.' },
    { title: 'Iraq Reconstruction Demand', desc: 'Jordan is the primary pharmaceutical supply corridor into Iraq — KIMADIA demand supports Jordanian export volume.' },
    { title: 'Refugee & Donor Health Programs', desc: 'International donor-funded health programmes add procurement volume beyond the national budget.' },
  ],
  bionixusServices: [
    { title: 'Physician Surveys & KOL Mapping', desc: 'Arabic-English fieldwork with Jordanian physicians across MOH, Royal Medical Services, university, and private hospitals.' },
    { title: 'Market Access & JFDA Strategy', desc: 'JFDA registration pathway analysis, JPD/MOH tender intelligence, and pricing benchmark studies.' },
    { title: 'Export Market Prioritisation', desc: 'For Jordanian manufacturers: GCC, Iraq, and Africa registration sequencing and partner identification.' },
    { title: 'Competitive Intelligence', desc: 'Monitoring launches, tender awards, and generic entry across Jordan and the Levant.' },
  ],
  faq: [
    { q: 'How many pharmaceutical companies operate in Jordan?', a: 'Jordan has around 16 licensed pharmaceutical manufacturers and dozens of importers and distributors. The leaders are Hikma Pharmaceuticals, Dar Al Dawa, MidPharma, APM, Hayat Pharmaceutical, Jordan River, Pharma International, and Amman Pharmaceutical Industries, alongside multinational scientific offices.' },
    { q: 'What is the size of Jordan\'s pharmaceutical market?', a: 'Jordan\'s domestic pharmaceutical market is approximately US$1.4–1.8 billion in 2026, but the industry\'s real weight is exports — over US$1 billion annually to 60+ countries, making pharmaceuticals one of Jordan\'s top export sectors.' },
    { q: 'Is Hikma a Jordanian company?', a: 'Yes. Hikma Pharmaceuticals was founded in Amman in 1978 by Samih Darwazah, and Jordan remains a major manufacturing and R&D base. Hikma is now headquartered in London, listed on the FTSE 100, and is one of the largest suppliers of generic injectables in the USA.' },
    { q: 'How do you register a pharmaceutical product with JFDA?', a: 'JFDA registration requires a full CTD dossier, GMP certification (with possible site inspection), CPP, Arabic labelling, and a local marketing authorisation holder. Timelines run 12–24 months, and pricing approval — among the region\'s strictest — precedes marketing.' },
    { q: 'Why does JFDA approval matter beyond Jordan?', a: 'Several Arab regulators treat JFDA approval as a trusted reference, accelerating registration in Iraq, the GCC, Libya, Yemen, and parts of Africa. Manufacturers often prioritise Jordan registration for this halo effect despite the small domestic market.' },
    { q: 'How does public drug procurement work in Jordan?', a: 'The Joint Procurement Department (JPD) runs consolidated tenders for MOH, Royal Medical Services, and university hospitals. Winning JPD tenders is the main route to public-sector volume; the private retail channel (~2,900 pharmacies) is served through national wholesalers.' },
  ],
  relatedLinks: [
    { to: '/pharmaceutical-companies-iraq', label: 'Pharmaceutical companies in Iraq' },
    { to: '/pharmaceutical-companies-saudi-arabia', label: 'Pharmaceutical companies in Saudi Arabia' },
    { to: '/pharmaceutical-companies-egypt', label: 'Pharmaceutical companies in Egypt' },
    { to: '/pharmaceutical-companies-uae', label: 'Pharmaceutical companies in UAE' },
    { to: '/gcc-market-access-guide', label: 'GCC market access guide 2026' },
    { to: '/mena-pharma-market-data', label: 'MENA pharmaceutical market data 2026' },
  ],
  sources: [
    'JFDA — Jordan Food and Drug Administration',
    'Jordanian Association of Pharmaceutical Manufacturers (JAPM)',
    'Company filings (Hikma plc, ASE-listed manufacturers)',
    'Joint Procurement Department tender records',
    'BioNixus proprietary research (Levant & MENA, 2024–2026)',
  ],
  publishedDate: '2026-08-22',
  modifiedDate: '2026-08-22',
  conversion: {
    routingHint: 'Mention JFDA registration or JPD tender priorities for a faster routed response.',
    emailSubject: 'Jordan pharma market research — BioNixus',
  },
};

const JordanPharmaCompanies = () => <CountryCompaniesGuide config={config} />;

export default JordanPharmaCompanies;
