import { CountryCompaniesGuide, type CountryCompaniesGuideConfig } from '@/components/seo/CountryCompaniesGuide';

const config: CountryCompaniesGuideConfig = {
  path: '/pharmaceutical-companies-morocco',
  countryName: 'Morocco',
  industry: 'pharmaceutical',
  title: 'Top Pharmaceutical Companies in Morocco (2026 Ranked List)',
  metaDescription:
    'Top pharmaceutical companies in Morocco ranked for 2026 — Sothema, Cooper Pharma, Laprophan, Pharma 5, DMP regulation, AMO reform and market size. By BioNixus.',
  h1: 'Pharmaceutical Companies in Morocco',
  introLead: 'Pharmaceutical companies in Morocco serve North Africa\'s second-largest pharma market and a growing Francophone-Africa export platform',
  introRest: 'This guide covers Sothema, Cooper Pharma, Laprophan and the other major manufacturers, MNC offices, DMP regulation, AMO insurance reform, and a market of roughly $2–2.5 billion.',
  stats: [
    { value: '~$2–2.5B', label: 'Pharmaceutical market value 2026' },
    { value: '~37M', label: 'Population' },
    { value: '~70%', label: 'Local production share (volume)' },
    { value: '12–24 mo', label: 'DMP registration timeline' },
  ],
  quickAnswer: {
    marketSize: 'approximately USD 2–2.5 billion',
    growthRate: '~6–7% YoY',
    regulatorLabel: 'the Direction du Médicament et de la Pharmacie (DMP) under the Ministry of Health',
    extraSentence: 'AMO universal insurance rollout and Francophone-Africa export demand are the two structural growth stories.',
  },
  marketOverviewParagraphs: [
    'Morocco is North Africa\'s second-largest pharmaceutical market after Egypt, valued at approximately US$2–2.5 billion in 2026 for a population of 37 million. Local manufacturing covers roughly 70% of volume through some 50 licensed plants concentrated around Casablanca, with the sector ranked among Africa\'s most developed by WHO maturity criteria.',
    'The Direction du Médicament et de la Pharmacie (DMP) within the Ministry of Health regulates registration, pricing, and pharmacovigilance. Morocco applies government-decreed price ceilings referenced to a six-country basket, and the AMO (Assurance Maladie Obligatoire) generalisation programme is progressively extending insurance coverage to the whole population — the single biggest demand-side driver.',
    'Sothema, Cooper Pharma, Laprophan, Pharma 5, and Galenica lead local manufacturing; several also export across Francophone West Africa. Multinationals operate through local plants (Sanofi\'s Maphar heritage) or scientific offices in Casablanca.',
  ],
  companies: [
    { name: 'Sothema', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Multi-therapeutic, insulin, injectables', notes: 'Largest listed Moroccan pharma; West Africa unit in Dakar' },
    { name: 'Cooper Pharma', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Branded generics, consumer health', notes: 'Century-old manufacturer; Africa expansion strategy' },
    { name: 'Laprophan', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Generics, respiratory, pain', notes: 'Major Casablanca manufacturer with export reach' },
    { name: 'Pharma 5', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Generics, hepatitis C, oncology', notes: 'Known for affordable HCV generics; Africa-focused' },
    { name: 'Galenica', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Generics, cardiology', notes: 'Established local generics player' },
    { name: 'Afric-Phar', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Generics, OTC', notes: 'Local manufacturer with African exports' },
    { name: 'Zenith Pharma', hq: 'Morocco', type: 'Local Manufacturer', therapeuticAreas: 'Generics, injectables', notes: 'Growing local producer' },
    { name: 'Sanofi Maroc (Maphar)', hq: 'France / Morocco', type: 'MNC Office', therapeuticAreas: 'Diabetes, vaccines, consumer health', notes: 'Historic local manufacturing via Maphar network' },
    { name: 'Pfizer', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Oncology, vaccines, inflammation', notes: 'Casablanca office; innovator portfolio' },
    { name: 'Novartis', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, immunology, ophthalmology', notes: 'Maghreb cluster presence' },
    { name: 'Roche', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, haematology, diagnostics', notes: 'Oncology supplier to CHU and private oncology centres' },
    { name: 'GSK', hq: 'UK', type: 'MNC Office', therapeuticAreas: 'Vaccines, respiratory', notes: 'Vaccine and respiratory franchise' },
    { name: 'AstraZeneca', hq: 'UK / Sweden', type: 'MNC Office', therapeuticAreas: 'Oncology, respiratory, CVRM', notes: 'Growing Maghreb oncology presence' },
    { name: 'MSD', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Oncology, vaccines', notes: 'Innovator oncology and vaccines' },
    { name: 'Hikma Pharmaceuticals', hq: 'Jordan / UK', type: 'Regional', therapeuticAreas: 'Injectables, generics', notes: 'MENA player active in Moroccan hospitals' },
    { name: 'Julphar', hq: 'UAE', type: 'Regional', therapeuticAreas: 'Generics, consumer health', notes: 'Gulf generics supplier' },
    { name: 'Maphar Distribution', hq: 'Morocco', type: 'Distributor', therapeuticAreas: 'Wholesale & logistics', notes: 'Leading national distributor network' },
    { name: 'Sophadial / regional wholesalers', hq: 'Morocco', type: 'Distributor', therapeuticAreas: 'Wholesale distribution', notes: 'Serve ~12,000 retail pharmacies nationwide' },
  ],
  categoryBlurbs: {
    local: 'Around 50 licensed plants — led by Sothema, Cooper Pharma, Laprophan, Pharma 5, and Galenica — cover ~70% of domestic volume and increasingly export to Francophone West Africa.',
    mnc: 'Multinationals combine Casablanca scientific offices with local manufacturing partnerships; Sanofi\'s Maphar heritage gives it the deepest local footprint.',
    regional: 'MENA players such as Hikma and Julphar compete in hospital injectables and retail generics.',
    distributor: 'A consolidated wholesale layer (Maphar Distribution, Sophadial, and regional grossisteries) serves roughly 12,000 pharmacies.',
  },
  regulator: {
    short: 'DMP',
    full: 'Direction du Médicament et de la Pharmacie (Ministry of Health)',
    registrationTimeline: '12–24 months',
    renewalPeriod: '5 years',
    pricingModel: 'Government-decreed price ceilings referenced to a 6-country external basket (incl. France, Spain, Turkey, Saudi Arabia)',
    requirements: [
      'CTD dossier in French via DMP',
      'GMP certificate; site inspection possible',
      'Certificate of Pharmaceutical Product (CPP)',
      'French/Arabic labelling',
      'Local pharmaceutical establishment (établissement pharmaceutique) required',
      'Price approval by decree before marketing',
    ],
    note: 'AMO generalisation is extending mandatory health insurance to the full population, expanding reimbursed drug demand through CNSS/CNOPS channels. Public procurement runs through Ministry of Health tenders; the private channel remains the value majority.',
  },
  growthDrivers: [
    { title: 'AMO Universal Insurance', desc: 'The AMO generalisation programme is bringing millions of newly insured patients into reimbursed pharmaceutical demand.' },
    { title: 'Local Manufacturing Policy', desc: 'Government policy favours local production and positions Morocco as a vaccine and biosimilar manufacturing hub for Africa.' },
    { title: 'Francophone Africa Exports', desc: 'Moroccan manufacturers use shared language, banking, and logistics ties to grow exports across West Africa.' },
    { title: 'Oncology & Specialty Growth', desc: 'Cancer centre expansion (Institut National d\'Oncologie network) drives innovative oncology uptake.' },
    { title: 'Vaccine Sovereignty Projects', desc: 'The SENSYO Pharmatech project targets large-scale vaccine and biologic fill-finish capacity near Casablanca.' },
    { title: 'Medical Infrastructure Investment', desc: 'New CHU university hospitals in Tangier, Agadir, and Laâyoune expand tertiary pharmaceutical demand.' },
  ],
  bionixusServices: [
    { title: 'Physician Surveys & KOL Mapping', desc: 'French-Arabic fieldwork with Moroccan physicians across CHU, military, and private clinics.' },
    { title: 'Market Access & DMP Strategy', desc: 'DMP registration pathway analysis, price-decree benchmarking, and AMO reimbursement intelligence.' },
    { title: 'Competitive Intelligence', desc: 'Tracking launches, MOH tender awards, and local manufacturer pipelines across the Maghreb.' },
    { title: 'Maghreb & Africa Benchmarking', desc: 'Comparative entry analysis across Morocco, Algeria, Tunisia, Egypt, and Francophone West Africa.' },
  ],
  faq: [
    { q: 'How many pharmaceutical companies operate in Morocco?', a: 'Morocco has around 50 licensed pharmaceutical manufacturing sites and 40+ importers. Leaders include Sothema, Cooper Pharma, Laprophan, Pharma 5, and Galenica among locals, with Sanofi (Maphar), Pfizer, Novartis, Roche, GSK, AstraZeneca, and MSD among multinationals.' },
    { q: 'What is the size of Morocco\'s pharmaceutical market?', a: 'Morocco\'s pharmaceutical market is valued at approximately US$2–2.5 billion in 2026, growing ~6–7% annually — North Africa\'s second-largest market after Egypt. Local production covers about 70% of volume.' },
    { q: 'Who regulates pharmaceuticals in Morocco?', a: 'The Direction du Médicament et de la Pharmacie (DMP) within the Ministry of Health handles registration, pricing, quality control, and pharmacovigilance. Registration takes 12–24 months and requires a local pharmaceutical establishment.' },
    { q: 'How does drug pricing work in Morocco?', a: 'Prices are set by government decree using external reference pricing against a six-country basket including France, Spain, Turkey, and Saudi Arabia. The 2014 pricing reform cut prices significantly and the framework has been periodically revised since.' },
    { q: 'What is AMO and why does it matter for pharma?', a: 'AMO (Assurance Maladie Obligatoire) is Morocco\'s mandatory health insurance, now being generalised to the entire population including the former RAMED (public assistance) beneficiaries. It expands reimbursed pharmaceutical demand through CNSS and CNOPS payer channels — the market\'s biggest structural growth driver.' },
    { q: 'Can Morocco serve as an Africa export base?', a: 'Yes. Moroccan manufacturers export across Francophone West Africa, supported by banking, logistics, and free-trade links. Government-backed projects such as SENSYO Pharmatech aim to make Morocco a vaccine and biologics manufacturing hub for the continent.' },
  ],
  relatedLinks: [
    { to: '/pharmaceutical-companies-egypt', label: 'Pharmaceutical companies in Egypt' },
    { to: '/pharmaceutical-companies-uae', label: 'Pharmaceutical companies in UAE' },
    { to: '/pharmaceutical-companies-saudi-arabia', label: 'Pharmaceutical companies in Saudi Arabia' },
    { to: '/insights/top-market-research-companies-morocco-2026', label: 'Top market research companies in Morocco 2026' },
    { to: '/mena-pharma-market-data', label: 'MENA pharmaceutical market data 2026' },
    { to: '/gcc-market-access-guide', label: 'GCC market access guide 2026' },
  ],
  sources: [
    'DMP — Direction du Médicament et de la Pharmacie (Ministère de la Santé)',
    'Les Industriels du Médicament au Maroc (LEMM) publications',
    'AMO/CNSS coverage statistics',
    'Company filings (Casablanca Stock Exchange)',
    'BioNixus proprietary research (Maghreb & MENA, 2024–2026)',
  ],
  publishedDate: '2026-08-22',
  modifiedDate: '2026-08-22',
  conversion: {
    routingHint: 'Mention DMP registration or AMO reimbursement priorities for a faster routed response.',
    emailSubject: 'Morocco pharma market research — BioNixus',
  },
};

const MoroccoPharmaCompanies = () => <CountryCompaniesGuide config={config} />;

export default MoroccoPharmaCompanies;
