import { CountryCompaniesGuide, type CountryCompaniesGuideConfig } from '@/components/seo/CountryCompaniesGuide';

const config: CountryCompaniesGuideConfig = {
  path: '/pharmaceutical-companies-south-korea',
  countryName: 'South Korea',
  industry: 'pharmaceutical',
  title: 'Top Pharmaceutical Companies in South Korea (2026 Ranked)',
  metaDescription:
    'Top pharmaceutical companies in South Korea ranked for 2026 — Samsung Biologics, Celltrion, Yuhan, Hanmi, MFDS regulation, HIRA pricing and market size. By BioNixus.',
  h1: 'Pharmaceutical Companies in South Korea',
  introLead: 'Pharmaceutical companies in South Korea combine a sophisticated domestic market with the world\'s leading biosimilar and biomanufacturing cluster',
  introRest: 'This guide ranks Samsung Biologics, Celltrion, Yuhan, Hanmi and the other majors, and explains MFDS registration, HIRA reimbursement, and a market of roughly $23–26 billion.',
  stats: [
    { value: '~$23–26B', label: 'Pharmaceutical market value 2026' },
    { value: '#1', label: 'Global biologics CDMO capacity (Samsung)' },
    { value: '~51M', label: 'Population (universal NHIS coverage)' },
    { value: '10–14 mo', label: 'MFDS registration timeline' },
  ],
  quickAnswer: {
    marketSize: 'approximately USD 23–26 billion',
    growthRate: '~5–6% YoY',
    regulatorLabel: 'the MFDS (Ministry of Food and Drug Safety)',
    extraSentence: 'Korea is simultaneously a demanding HIRA-controlled access market and the world\'s biologics manufacturing powerhouse via Samsung Biologics and Celltrion.',
  },
  marketOverviewParagraphs: [
    'South Korea\'s pharmaceutical market is valued at approximately US$23–26 billion in 2026, backed by universal National Health Insurance Service (NHIS) coverage for 51 million people. HIRA (Health Insurance Review & Assessment Service) runs one of Asia\'s most rigorous pricing and reimbursement gatekeeping systems, with positive-list coverage and aggressive price negotiations.',
    'The MFDS (Ministry of Food and Drug Safety) reviews registrations in 10–14 months, accepts global clinical packages with Korean bridging where needed, and runs expedited pathways for innovative and orphan drugs.',
    'Korea\'s global significance is biomanufacturing: Samsung Biologics operates the world\'s largest biologics CDMO capacity, and Celltrion pioneered biosimilar monoclonal antibodies. Domestic innovators Yuhan (lazertinib out-licensed to J&J), Hanmi, Daewoong, HK inno.N, and GC Biopharma increasingly generate globally licensed assets, while SK Biopharmaceuticals took cenobamate to the US market directly.',
  ],
  companies: [
    { name: 'Samsung Biologics / Samsung Bioepis', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Biologics CDMO, biosimilars', notes: 'World\'s largest biologics CDMO; Bioepis biosimilar portfolio' },
    { name: 'Celltrion', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Biosimilars (mAbs), novel biologics', notes: 'Biosimilar mAb pioneer (Remsima/infliximab)' },
    { name: 'Yuhan Corporation', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Oncology, generics, consumer', notes: 'Korea\'s largest traditional pharma; lazertinib→J&J (Lazcluze)' },
    { name: 'Hanmi Pharmaceutical', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Metabolic, oncology, biologics platforms', notes: 'LAPSCOVERY platform; multiple global out-licenses' },
    { name: 'Daewoong Pharmaceutical', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'GI (fexuprazan), botulinum toxin, generics', notes: 'Global expansion of Fexuclue and Nabota' },
    { name: 'GC Biopharma (Green Cross)', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Plasma, vaccines, rare disease', notes: 'Plasma derivatives and vaccine leader' },
    { name: 'SK Biopharmaceuticals', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'CNS (cenobamate)', notes: 'Direct US commercialisation of Xcopri' },
    { name: 'HK inno.N', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'GI (tegoprazan), hospital products', notes: 'K-CAB global licensing footprint' },
    { name: 'Chong Kun Dang (CKD)', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Generics, biosimilars, novel assets', notes: 'Top-5 domestic; Novartis licensing deal' },
    { name: 'Boryung', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Cardiovascular, oncology', notes: 'Kanarb hypertension franchise' },
    { name: 'Dong-A ST', hq: 'South Korea', type: 'Local Manufacturer', therapeuticAreas: 'Generics, biosimilars, novel research', notes: 'Established domestic innovator' },
    { name: 'Pfizer Korea', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Oncology, vaccines, inflammation', notes: 'Major MNC presence in Seoul' },
    { name: 'MSD Korea', hq: 'USA', type: 'MNC Office', therapeuticAreas: 'Oncology, vaccines', notes: 'Keytruda HIRA-listed franchise' },
    { name: 'Roche Korea', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, haematology', notes: 'Oncology leader in tertiary hospitals' },
    { name: 'Novartis Korea', hq: 'Switzerland', type: 'MNC Office', therapeuticAreas: 'Oncology, immunology, gene therapy', notes: 'Broad innovative portfolio' },
    { name: 'AstraZeneca Korea', hq: 'UK / Sweden', type: 'MNC Office', therapeuticAreas: 'Oncology, respiratory, CVRM', notes: 'Tagrisso franchise strength' },
    { name: 'Geo-Young', hq: 'South Korea', type: 'Distributor', therapeuticAreas: 'Pharmaceutical wholesale', notes: 'Largest Korean pharmaceutical distributor' },
    { name: 'Baeksang / Jeil wholesale networks', hq: 'South Korea', type: 'Distributor', therapeuticAreas: 'Wholesale distribution', notes: 'Serve hospitals and ~24,000 pharmacies' },
  ],
  categoryBlurbs: {
    local: 'Korean companies span biomanufacturing giants (Samsung Biologics, Celltrion), traditional leaders (Yuhan, CKD, Dong-A, Boryung), and innovation-driven players (Hanmi, SK Biopharm, HK inno.N, Daewoong, GC Biopharma) with growing global licensing income.',
    mnc: 'MNCs hold the innovative oncology and vaccine segments, navigating HIRA\'s demanding positive-list reimbursement and risk-sharing agreements.',
    regional: 'The competitive set is domestic + global; Japanese and Chinese players participate mainly via licensing.',
    distributor: 'Geo-Young leads a consolidated wholesale sector distributing to tertiary hospitals and ~24,000 community pharmacies.',
  },
  regulator: {
    short: 'MFDS',
    full: 'Ministry of Food and Drug Safety',
    registrationTimeline: '10–14 months',
    renewalPeriod: '5 years',
    pricingModel: 'HIRA positive-list reimbursement with price negotiation (NHIS); risk-sharing agreements for high-cost drugs',
    requirements: [
      'CTD dossier via MFDS',
      'Korean bridging data where ethnic sensitivity indicated',
      'Korea Marketing Authorization Holder / local entity',
      'GMP certification incl. foreign site inspection',
      'Korean labelling and insert',
      'HIRA reimbursement dossier separate — economic evaluation required',
    ],
    note: 'HIRA\'s cost-effectiveness assessment and NHIS price negotiation are the commercial gatekeepers — expect reference pricing against lowest-in-basket and mandatory price cuts at volume thresholds. Risk-sharing agreements (refund, expenditure-cap) enable listing of high-cost oncology and rare-disease assets.',
  },
  growthDrivers: [
    { title: 'Biomanufacturing Superpower', desc: 'Samsung Biologics\' capacity expansion and Celltrion\'s biosimilar pipeline anchor global biologics supply chains in Incheon.' },
    { title: 'Global Licensing Engine', desc: 'Korean-origin assets (lazertinib, cenobamate, tegoprazan, fexuprazan) now generate multi-billion-dollar global deals.' },
    { title: 'Aging & Chronic Care', desc: 'Korea is aging faster than any OECD country — oncology, neurology, and chronic-disease demand grows structurally.' },
    { title: 'Government Bio-Vision Investment', desc: 'National bio-health strategy targets K-bio as a top export industry with R&D tax and cluster incentives.' },
    { title: 'Clinical Trial Hub', desc: 'Seoul is a top-5 global clinical trial city — tertiary hospital networks accelerate enrolment and KOL influence.' },
    { title: 'Digital Health & AI Adoption', desc: 'World-leading hospital informatics create rapid uptake channels for companion diagnostics and digital therapeutics.' },
  ],
  bionixusServices: [
    { title: 'Physician Surveys & KOL Mapping', desc: 'Korean-language fieldwork with physicians across Big-5 Seoul tertiary hospitals and regional centres.' },
    { title: 'Market Access & HIRA Strategy', desc: 'Reimbursement dossier intelligence, risk-sharing agreement benchmarking, and NHIS price negotiation modelling.' },
    { title: 'Competitive Intelligence', desc: 'Tracking Korean biosimilar pipelines, licensing deals, and MNC portfolio moves.' },
    { title: 'Korea vs Global Benchmarking', desc: 'Launch sequencing analysis for teams weighing Korea against Japan, China, and Western markets.' },
  ],
  faq: [
    { q: 'What are the largest pharmaceutical companies in South Korea?', a: 'The largest Korean pharmaceutical companies in 2026 are Samsung Biologics (biologics CDMO), Celltrion (biosimilars), Yuhan, Hanmi, Daewoong, GC Biopharma, Chong Kun Dang, SK Biopharmaceuticals, HK inno.N, and Dong-A ST. Samsung Biologics is the world\'s largest biologics contract manufacturer.' },
    { q: 'What is the size of South Korea\'s pharmaceutical market?', a: 'South Korea\'s pharmaceutical market is valued at approximately US$23–26 billion in 2026, growing 5–6% annually, with universal NHIS insurance covering the full 51-million population.' },
    { q: 'Who regulates pharmaceuticals in South Korea?', a: 'The MFDS (Ministry of Food and Drug Safety) handles registration in 10–14 months. Reimbursement is separate: HIRA assesses cost-effectiveness and the NHIS negotiates price — the true commercial gatekeepers.' },
    { q: 'Why is Korea important for global biologics?', a: 'Samsung Biologics operates the world\'s largest biologics CDMO capacity and manufactures for most top-20 global pharma companies, while Celltrion and Samsung Bioepis pioneered biosimilar monoclonal antibodies. The Songdo/Incheon cluster is a global biomanufacturing hub.' },
    { q: 'How does drug reimbursement work in Korea?', a: 'Korea uses a positive list: after MFDS approval, manufacturers submit a HIRA reimbursement dossier with economic evaluation, then negotiate price with NHIS. High-cost drugs increasingly list through risk-sharing agreements (refunds or expenditure caps). Prices face cuts at volume-growth thresholds.' },
    { q: 'Can foreign companies run trials and launch in Korea easily?', a: 'Yes — Seoul is a top global clinical trial hub with fast enrolment in Big-5 tertiary hospitals. MFDS accepts global packages (sometimes with Korean bridging), and a local MAH entity or partner handles registration and distribution.' },
  ],
  relatedLinks: [
    { to: '/south-korea-healthcare-market-report', label: 'South Korea healthcare market report 2026' },
    { to: '/south-korea-medical-devices-market-report', label: 'South Korea medical devices market report' },
    { to: '/pharmaceutical-companies-japan', label: 'Pharmaceutical companies in Japan' },
    { to: '/pharmaceutical-companies-china', label: 'Pharmaceutical companies in China' },
    { to: '/pharmaceutical-companies-singapore', label: 'Pharmaceutical companies in Singapore' },
    { to: '/gcc-market-access-guide', label: 'GCC market access guide 2026' },
  ],
  sources: [
    'MFDS — Ministry of Food and Drug Safety',
    'HIRA reimbursement decisions and NHIS negotiations',
    'KPBMA (Korea Pharmaceutical and Bio-Pharma Manufacturers Association)',
    'Company filings (KRX-listed manufacturers)',
    'BioNixus proprietary research (Korea & Asia, 2024–2026)',
  ],
  publishedDate: '2026-08-22',
  modifiedDate: '2026-08-22',
  conversion: {
    routingHint: 'Mention MFDS registration or HIRA reimbursement strategy for a faster routed response.',
    emailSubject: 'South Korea pharma market research — BioNixus',
  },
};

const SouthKoreaPharmaCompanies = () => <CountryCompaniesGuide config={config} />;

export default SouthKoreaPharmaCompanies;
